### ISSUE TITLE
Add nodejs code to this repo

### ISSUE THREAD

**Issue by bforbis** [snowflakedb/snowflake-connector-nodejs#1]
Are there plans of adding the code for the nodejs connector to this repo? I'd like to make pull requests to update the `snowflake-sdk` package.

**Comment by smtakeda** [comment]
Unfortunately it is not in the short team plan. At the moment, feel free to file a support at https://support.snowflake.net/s/snowflake-support. Thank you.

**Comment by smtakeda** [comment]
Done!
