### ISSUE TITLE
Update request dependency to latest version

### ISSUE THREAD

**Issue by bforbis** [snowflakedb/snowflake-connector-nodejs#10]
The current version of `request` that snowflake-sdk depends on is old and is now has deprecation warnings for some of its dependencies.

```
npm WARN deprecated boom@4.3.1: This version is no longer maintained. Please upgrade to the latest version.
```

Updating to the latest version of the request package will fix these deprecation warnings.

Is there a specific reason why a pinned version is being used instead of allowing for minor/patch changes in the dependency?

**Comment by smtakeda** [comment]
no, let me try upgrading to the latest one.
Looks like no regression is observed.
