### ISSUE TITLE
SNOW-172413: OAuth support for node.js driver

### ISSUE THREAD

**Issue by fimbulvetr** [snowflakedb/snowflake-connector-nodejs#111]
Currently the node.js driver does not support access tokens for authentication. This is limited to the *bdc/go/python driver. We have the need for this node.js driver to support access token. Our app and backend are written in Node, for now we will have to use a different language such as Go in order to run queries using a user's access token. This is not ideal as it is not aligned with our ecosystem goals.

**Comment by sfc-gh-dszmolka** [comment]
OAuth authentication support released with v1.6.0, thank you for your patience
