### ISSUE TITLE
SNOW-186411: Fetch timeout

### ISSUE THREAD

**Issue by idahopotato1** [snowflakedb/snowflake-connector-nodejs#122]
When I made a post request from react to express, I could see query running in snowflake. However, it the fetch would stop and timeout after exactly 2 minutes without exceptions. I could see that query is still running and would finish in snowflake. But since the fetch stopped after 2 minutes, nothing would be delivered to the front end. 
Anybody might know why this happened? 

Thanks

**Comment by ajpaon** [comment]
Hi @idahopotato1, I have been dealing with this same issue. Did you ever find a resolution?
