### ISSUE TITLE
SNOW-291733: Get error when trying to create connection

### ISSUE THREAD

**Issue by mharnicher-cxp** [snowflakedb/snowflake-connector-nodejs#146]
Please answer these questions before submitting your issue. Thanks!

1. What version of NodeJS are you using (`node --version` and `npm --version`)?
```
executionEnvironment': 'CLI', 'pyversion': '3.8.7', 'samcliVersion': '1.18.1', 'runtimes': ['nodejs12.x']
```
2. What operating system and processor architecture are you using?
* Mac - System Version: macOS 11.2 (20D64)
* Running in an aws sam cli execution environment

3. What are the component versions in the environment (`npm list`)?

4. What did you do?
* This happens when i'm trying to create the connection (I'm using a promise wrapper library snowflake-promise, but i get the same error when directly using snowflake-sdk.
```
const { Snowflake } = require('snowflake-promise');
const { SSM } = require('aws-sdk');

let password;
exports.handler = async function (event, context) {
    // Store password in memory, cloudformation can't pull secure strings at the time of this writing
    if (!password) {
        let ssm = new SSM();
        let response = await ssm.getParameter({
            Name: '/snowflake/password',
            WithDecryption: true,
        }).promise();
        
        password = response.Parameter.Value
    }

    const snowflake = new Snowflake({
        account: process.env.SNOWFLAKE_ACCOUNT,
        username: process.env.SNOWFLAKE_USERNAME,
        database: process.env.SNOWFLAKE_DATABASE,
        schema: process.env.SNOWFLAKE_SCHEMA,
        password,
    });

    await snowflake.connect();
    const rows = await snowflake.execute(
        'SELECT CURRENT_VERSION()',
    );
    
    return rows;    
}
```

5. What did you expect to see?
* The rows to return
6. What did you see instead?
```
{
  "errorType": "Error",
  "errorMessage": "Cannot find module './lib/decorators/timed'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
  "trace": [
    "Error: Cannot find module './lib/decorators/timed'",
    "Require stack:",
    "- /var/task/index.js",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/index.js",
    "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:667:27)",
    "    at Module.require (internal/modules/cjs/loader.js:887:19)",
    "    at require (internal/modules/cjs/helpers.js:74:18)",
    "    at /var/task/index.js:25259:19",
    "    at /var/task/index.js:25374:23",
    "    at /var/task/index.js:25258:5",
    "    at /var/task/index.js:25373:5",
    "    at /var/task/index.js:4:5",
    "    at /var/task/index.js:74906:14"
  ]
}
```
7. Add this to get standard output.
 
```
var snowflake = require('./snowflake');
snowflake.configure(
{
  logLevel: 'trace'
});
```

* no difference

**Comment by sfc-gh-kwagner** [comment]
Hi @mharnicher-cxp can you reach out to Snowflake support for help with this issue?

**Comment by mharnicher-cxp** [comment]
Sure can!

**Comment by pdomala** [comment]
Any update from Snowflake on this issue @mharnicher-cxp ? We are seeing the same error while creating snowflake connection.

**Comment by markandrus** [comment]
I am using esbuild, and I also hit this. The issue for esbuild, as far as I can tell, is that snowflake-sdk depends on [requestretry](https://github.com/FGRibreau/node-request-retry), which in turn depends on [when](https://github.com/cujojs/when). when [wraps itself up]() in what looks like (AFAICT) a CommonJS/AMD compatibility layer. Anyway, it looks too complicated for esbuild to statically analyze (due to the way the `require` is routed around), so if you run esbuild on it, you see the following:

```
$ npx esbuild --bundle node_modules/when/when.js --platform=node | head -n 10
// node_modules/when/when.js
(function(define2) {
  "use strict";
  define2(function(require2) {
    var timed = require2("./lib/decorators/timed");
    var array = require2("./lib/decorators/array");
    var flow = require2("./lib/decorators/flow");
    var fold = require2("./lib/decorators/fold");
    var inspect = require2("./lib/decorators/inspect");
    var generate = require2("./lib/decorators/iterate");
```

Note the `require2` calls are unchanged. esbuild normally turns these into dedicated functions for importing the various dependencies. They're missing, though, so the bundle is not going to work.

**Comment by markandrus** [comment]
`requestretry@6.0.0` is now released with the dependency on `when` removed. So we should try updating the Snowflake library next.
