### ISSUE TITLE
OCSP is randomly failing in latest release

### ISSUE THREAD

**Issue by mhseiden** [snowflakedb/snowflake-connector-nodejs#16]
We are seeing the following error bubble up on occasion. It looks like it's coming from the `ocsp` library that y'all are using.

```
ERROR: [9:34:45.3445 AM]: OCSP validation failed: Error: Unsupported type: object at: (shallow)
```

**Comment by smtakeda** [comment]
hmm, sounds like garbage was returned from OCSP responder... The driver needs retry.

Currently NodeJS doesn't cache the OCSP response nor uses the OCSP cache server, OCSP check is not as stable as JDBC, ODBC, Python Connector.  We'll add it in the earliest opportunity.
For workaround, use `insecureConnect` parameter to skip OCSP check.
```
var connectionOptions =
{
  account: testaccount, ... , insecureConnect: true
}
```
Note `insecureConnect=true` will still do 1) verify the certificate signature, 2) check validity, 3) ensure the certificate is associated with the hostname.

**Comment by natesilva** [comment]
Workaround: the `insecureConnect` option needs to be passed to `snowflake.configure(...)`, not to the `createConnection` function.

```
snowflake.configure({insecureConnect: true});
var connection = snowflake.createConnection(...);
```

**Comment by rem7** [comment]
```  name: 'NetworkError',
  code: 401001,
  message: 'Network error. Could not reach Snowflake.',
  cause: Error: Bad OCSP response status: try_later
```
seeing the same issue

**Comment by moniecodes** [comment]
Is there any update on this issue?  

What is the impact of using` insecureConnect:true`.  I assume we want the OCSP checks when using node client?

**Comment by NoxHarmonium** [comment]
FWIW I was having the `OCSP validation failed: Error: Unsupported type: object at: (shallow)` error and it turned out to be the version of `asn1.js` that was getting resolved. I think that the version range isn't restrictive enough so if another library uses `asn1.js` but an incompatible version it can break this library. I fixed it by adding:

```
  "resolutions": {
    "asn1.js": "^5.4.1"
  },
```

To my package.json file (I use Yarn, the syntax might vary for NPM). I'm not sure if it is the same issue you are having but it might help.

**Comment by bajohn** [comment]
> FWIW I was having the `OCSP validation failed: Error: Unsupported type: object at: (shallow)` error and it turned out to be the version of `asn1.js` that was getting resolved. I think that the version range isn't restrictive enough so if another library uses `asn1.js` but an incompatible version it can break this library. I fixed it by adding:
> 
> ```
>   "resolutions": {
>     "asn1.js": "^5.4.1"
>   },
> ```
> 
> To my package.json file (I use Yarn, the syntax might vary for NPM). I'm not sure if it is the same issue you are having but it might help.

Thank you! This worked for me, in Node I just set the following in package.json dependencies:
```
    "asn1": "^0.2.4",
```
, delete my package-lock.json / node_modules to make sure a lower version wasn't still being used, then rerun `npm install`. Snowflake is now connecting correctly.

**Comment by markandrus** [comment]
@NoxHarmonium @bajohn thanks for pointing me in the right direction. I dove into snowflake-sdk's ocsp and asn1.js dependencies. It looks really messy:

* ocsp@1.2.0 depends on asn1.js-rfc5280@^2.0.0
* ocsp@1.2.0 depends on asn1.js-rfc2560@^4.0.0
* asn1.js-rfc2560@4.0.6 depends on asn1.js-rfc5280@^2.0.0
    * asn1.js-rfc5280@2.0.1 depends on asn1.js@^4.5.0
* snowflake-sdk@1.6.4 depends on asn1.js-rc2560@^5.0.0
* snowflake-sdk@1.6.4 depends on asn1.js-rfc5280@^3.0.0
* asn1.js-rfc2560@5.0.1 depends on asn1.js-rfc5280@^3.0.0
    * asn1.js-rfc5280@3.0.0 depends on asn1.js@^5.0.0
* snowflake-sdk@1.6.4 depends on ocsp@^1.2.0
    * ocsp@1.2.0 depends on asn1.js@^4.8.0

In a recent install, I ended up with

* asn1.js@4.10.1 and asn1.js@5.4.1
* asn1.js-rfc5280@2.0.1 and asn1.js-rfc5280@3.0.0
* asn1.js-rfc2560@4.0.6 and asn1.js-rfc2560@5.0.1

So I can definitely see how this can cause problems. I think the issue would best be solved in ocsp and asn1.js, releasing packages that update to the latest versions (assuming they're compatible). Then, I'd expect to just need

* asn1.js@5.4.1
* asn1.js-rfc5280@3.0.0
* asn1.js-rfc2560@5.0.1

**Comment by wpride** [comment]
> @NoxHarmonium @bajohn thanks for pointing me in the right direction. I dove into snowflake-sdk's ocsp and asn1.js dependencies (with the help of `yarn why`). It looks really messy:
> 
> * ocsp@1.2.0 depends on asn1.js-rfc5280@^2.0.0
> * ocsp@1.2.0 depends on asn1.js-rfc2560@^4.0.0
> * asn1.js-rfc2560@4.0.6 depends on asn1.js-rfc5280@^2.0.0
>   
>   * asn1.js-rfc5280@2.0.1 depends on asn1.js@^4.5.0
> * snowflake-sdk@1.6.4 depends on asn1.js-rc2560@^5.0.0
> * snowflake-sdk@1.6.4 depends on asn1.js-rfc5280@^3.0.0
> * asn1.js-rfc2560@5.0.1 depends on asn1.js-rfc5280@^3.0.0
>   
>   * asn1.js-rfc5280@3.0.0 depends on asn1.js@^5.0.0
> * snowflake-sdk@1.6.4 depends on ocsp@^1.2.0
>   
>   * ocsp@1.2.0 depends on asn1.js@^4.8.0
> 
> In a recent install, I ended up with
> 
> * asn1.js@4.10.1 and asn1.js@5.4.1
> * asn1.js-rfc5280@2.0.1 and asn1.js-rfc5280@3.0.0
> * asn1.js-rfc2560@4.0.6 and asn1.js-rfc2560@5.0.1
> 
> So I can definitely see how this can cause problems. I think the issue would best be solved in ocsp and asn1.js, releasing packages that update to the latest versions (assuming they're compatible). Then, I'd expect to just need
> 
> * asn1.js@5.4.1
> * asn1.js-rfc5280@3.0.0
> * asn1.js-rfc2560@5.0.1
> 
> **UPDATE:** I can confirm that the following worked:
> 
> ```
> yarn set resolution --save 'asn1.js@npm:^4.8.0' ^5.0.0
> yarn set resolution --save 'asn1.js-rfc2560@npm:^4.0.0' ^5.0.0
> yarn set resolution --save 'asn1.js-rfc5280@npm:^2.0.0' ^3.0.0
> ```

You're a legend, this worked beautifully

**Comment by sfc-gh-dszmolka** [comment]
this very, very old issue should be hopefully resolved by now with the newer releases, which don't have the previous `ocsp` dependency (`v1.6.9` and up) 
thank you so much everyone for your contribution and help here. 

i'm closing this now but if you still find it being an issue in the more recent releases, please reopen it and we'll take a look.
