### ISSUE TITLE
Update node-uuid dependency to use uuid instead

### ISSUE THREAD

**Issue by bforbis** [snowflakedb/snowflake-connector-nodejs#2]
The [node-uuid](https://www.npmjs.com/package/node-uuid) package has been deprecated for quite some time now, and now throws deprecation warnings on install and during runtime.

This should be updated to use the [uuid](https://www.npmjs.com/package/uuid) package instead

**Comment by smtakeda** [comment]
Fixed. Will be released on v1.1.8
