### ISSUE TITLE
https_proxy_ocsp_agent can break https.request (outdated agent-base, https-proxy-agent)

### ISSUE THREAD

**Issue by kavika-1** [snowflakedb/snowflake-connector-nodejs#201]
Please answer these questions before submitting your issue. Thanks!

1. What version of NodeJS are you using (`node --version` and `npm --version`)?
Node: 12.22.1
Npm: 7.23.0 (but also breaks on 6)

2. What operating system and processor architecture are you using?
linux: Ubuntu 20.04.3 LTS, and amazon (lambda)

Basically under certain circumstances, calling requests that use `https.request` will fail due to the outdated agent-base library.  agent-base monkey patches `request.end` in `patch-core.js:12`.  The `Object.assign(..., _options)` on line 19 fails to copy fields that use getters/setters.

More recent (the latest) versions of agent-base +https-proxy-agent no longer have this code or problem.

However, would suggest ensuring a solution that only affects the requests issued by the snowflake driver, instead of all requests globally.

**Comment by joelfillmore** [comment]
The Snowflake SDK uses agent-base@4.3.0 which has a serious flaw: https://github.com/TooTallNate/node-agent-base/issues/29

It monkey patches the core node request code which can cause failures in other libraries which also use the standard node request object. In my case, just adding the snowflake sdk project causes a failure in our openid authentication library: https://github.com/panva/node-openid-client/issues/320

Newer versions of agent-base have eliminated the code patching. Snowflake should use at least agent-base@5 and preferably version 6.

In addition to the direct dependency on agent-base, there is also an indirect dependency https-proxy-agent which needs to be updated to remove the flawed agent-base:

```
npm list agent-base
├─┬ snowflake-sdk@1.6.5
│ ├── agent-base@4.3.0 
│ └─┬ https-proxy-agent@3.0.1
│   └── agent-base@4.3.0  deduped
```
