### ISSUE TITLE
SNOW-502598 Unable to execute statements in async mode (add async query execution capabilities)

### ISSUE THREAD

**Issue by gievln** [snowflakedb/snowflake-connector-nodejs#208]
Please answer these questions before submitting your issue. Thanks!

1. What version of NodeJS are you using (`node --version` and `npm --version`)?
node: `v14.18.0`
yarn: `1.22.10`

2. What operating system and processor architecture are you using?
For Prod env: [AWS Lambda](https://aws.amazon.com/lambda/)
For local testing:
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:      focal
```

3. What are the component versions in the environment (`npm list`)?
```
"snowflake-sdk": "1.6.3",
"@types/snowflake-sdk": "1.6.1"
```

Hey, is there a way to execute statements in async manner so that after starting a heavy procedure I would be able to monitor its status using snowflake's `query_history()` calls?
Looks like `snowflake-connector-nodejs`  doesn't allow to set `async` execution parameter to the inner SnowFlake API call on statement execution…
In general Snowflake REST API allows to execute sql statement in async mode `async:true` (see [here](https://docs.snowflake.com/en/developer-guide/sql-api/reference.html#query-parameters)) - this is an url parameter but it’s not allowed in NodeJs snowflake driver. I believe this is the place where we should be able to set async param:
```
...
url: Url.format(
        {
          pathname: '/queries/v1/query-request',
          search: QueryString.stringify(
            {
              requestId: statementContext.requestId,
              async: statementContext.async // <--- NEW LINE THAT DOESN'T EXIST AT THE MOMENT
            })
}),
```
source code is here: [https://github.com/snowflakedb/snowflake-connector-nodejs/blob/master/lib/connection/statement.js#L1134](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/master/lib/connection/statement.js#L1134)

Is there a plan to introduce this async flag support in `snowflake-connector-nodejs`? Or maybe someone could recommend other approach to achieve this asynchronous behavior?

**Comment by bjacques** [comment]
I see that [async queries are available for the Python driver](https://docs.snowflake.com/en/user-guide/python-connector-example.html#performing-an-asynchronous-query), but not Nodejs

**Comment by TomNachman** [comment]
will there be any support for NodeJS driver in the future for this?

**Comment by sfc-gh-dszmolka** [comment]
hi, we do have plans to support it in the future. unfortunately at this moment, i do not have any information on the timeline.

**Comment by sfc-gh-dszmolka** [comment]
reopened to be able to properly track the request

**Comment by sfc-gh-dszmolka** [comment]
Thank you all so much for bearing with us ! Got some good news: work is ongoing on this one, will update this comment once it gets into review.

**Comment by sfc-gh-dszmolka** [comment]
PR: https://github.com/snowflakedb/snowflake-connector-nodejs/pull/672

**Comment by sfc-gh-dszmolka** [comment]
PR #672 is merged and will be part of the upcoming October's release (hoping to release very soon)

**Comment by sfc-gh-dszmolka** [comment]
node.js driver version 1.9.1 released with the fix and is available on npm. thank you all for bearing with us !
