### ISSUE TITLE
Move aws-sdk to peer/optional dependency

### ISSUE THREAD

**Issue by AndrewBarba** [snowflakedb/snowflake-connector-nodejs#216]
Currently the aws-sdk is specified as a dependency for a single util function related to S3. The aws-sdk adds over 90mb of uncompressed code. Moving to a peer/optional dependency would allow for a much smaller bundle size on platforms like aws-lambda.

Another option is to move to v3 of the aws-sdk which allows for installing just the s3 SDK.

**Comment by gabdsg** [comment]
+1

**Comment by markandrus** [comment]
Just noticed this myself as I was migrating my code to AWS SDK v3. I still had this lingering AWS SDK v2 dependency hanging around…

**Comment by pranspach** [comment]
Why is this closed when the MR is still open?
