### ISSUE TITLE
This package loads 87 (!!) nested depencencies

### ISSUE THREAD

**Issue by OllieNilsen** [snowflakedb/snowflake-connector-nodejs#22]
I don't know if this can be considered a "bug", but it's causing me to write my own wrapper. As far as I can see, the package is just making some http(s) requests!

**Comment by lukesalamone** [comment]
@OllieNilsen Could you share your wrapper? The size of this sdk is obnoxious given its functionality.

**Comment by sfc-gh-dszmolka** [comment]
closing this old issue. if there's any specific action needed from our part or you encountered any bugs, please reopen it and share the details.
