### ISSUE TITLE
SNOW-514684: Connection Caching support to reduce number of prompts for authentication?

### ISSUE THREAD

**Issue by varun-dc** [snowflakedb/snowflake-connector-nodejs#236]
Please answer these questions before submitting your issue. Thanks!

1. What version of NodeJS are you using (`node --version` and `npm --version`)?
node 16.x.x

2. What operating system and processor architecture are you using?
Linux x86_64, MacOS ARM

3. What are the component versions in the environment (`npm list`)?
snowflake-sdk@1.6.4

The [docs](https://docs.snowflake.com/en/user-guide/admin-security-fed-auth-use.html#using-connection-caching-to-minimize-the-number-of-prompts-for-authentication-optional) state,

> Snowflake supports connection caching with the following drivers and connectors on macOS and Windows (currently, this feature is not supported on Linux):
>
> ODBC driver version 2.21.2 (or later)
> JDBC driver version 3.12.8 (or later)
> Snowflake Connector for Python 2.2.8 (or later)

But there is no support in the snowflake-connector-nodejs correct? Are there any plans to add support for connection caching in this package? If we submitted a pull request with this functionality, based on the work done in the python connector for example, will that be likely to be accepted into this package?

**Comment by sfc-gh-dszmolka** [comment]
thank you for submitting this issue! since it's still relevant (the driver does not support connection caching today) i raised this within the team for someone to take a look and estimate the work needed. will post any updates here, once available (which might take a while so thank you in advance for bearing with us)

**Comment by sfc-gh-dszmolka** [comment]
hi - at this moment, I'm unable to give any estimation, but syncing internally with the rest of the team and will share if there's any timelines visible. what I can say right now, that this item is definitely on the radar, just I cannot attach any estimation right now. thank you for bearing with us !

**Comment by hughess** [comment]
+1 this would be a big help

**Comment by Elliot2718** [comment]
+1 I'm also interested in seeing this implemented

**Comment by sfc-gh-dszmolka** [comment]
thank you everyone for bearing with us while the feature gets implemented. there's some bumps still needing to be ironed out, but we're actively working on the implementation. will keep this thread posted.

**Comment by sfc-gh-dszmolka** [comment]
apologies it taking so long, but being an entirely new feature which on top of it, operates on user credentials, we also had to go through a (lengthy) internal security review before the actual implementation. 

Feature PR's can be followed here:
* SSO token cache: #820 
* MFA token cache: #711  (I'll confirm if this is still the proper tracking PR)

As of now, I cannot give a specific ETA for the actual implementation, but syncing internally with the team and will update if there's any more specifics.

**Comment by sfc-gh-dszmolka** [comment]
PR #820 for SSO token caching is now merged, and will be part of the next upcoming release.
We keep working on the MFA token caching #711  too, to be released hopefully at the same time.

**Comment by sfc-gh-dszmolka** [comment]
released with Snowflake Node.JS driver v1.12.0 - thank you for bearing with us !

**Comment by supermacro** [comment]
Are there any docs on how to actually turn on connection caching for the nodejs driver? By looking at the source code, it seems like I need to specify 

- `clientStoreTemporaryCredential: true,`
- `credentialCacheDir: '..',`

but it's still not working (usng `externalbrowser` authenticator)

**Comment by sfc-gh-dszmolka** [comment]
docs are available (not too long ago , though) at https://docs.snowflake.com/en/developer-guide/node-js/nodejs-driver-authenticate#authentication-token-caching. 

please note that to successfully turn on the feature, you'll need to turn on _both_ the **server-side** and the **client-side** components. details in the doc - can you please give it a try?
