### ISSUE TITLE
Feature request: allow configuring connection- and request-level timeouts

### ISSUE THREAD

**Issue by markandrus** [snowflakedb/snowflake-connector-nodejs#247]
I've reviewed the Snowflake settings, but I cannot find a way to configure a timeout on the client. I would like to be able to configure typical connection- and request-level timeouts. This request is sort of related to #182, since both timeouts and retries relate to resiliency.

**Comment by sfc-gh-dszmolka** [comment]
commenting on this old issue before closing, in hope it helps someone stumbling on it.
connection option `timeout` (ms) can be used in the driver to provide a generic timeout for requests
```javascript
const connection = snowflake.createConnection({
    account: account,
    username: username,
 ..
    timeout: 2000, // 2 seconds
    application: application
});
```
also depending on the situation perhaps [STATEMENT_TIMEOUT_IN_SECONDS](https://docs.snowflake.com/en/sql-reference/parameters.html#statement-timeout-in-seconds) might also make sense. The latter is a Snowflake-side configuration, can be set on account, user, or even for a single session.

**Comment by BartusZak** [comment]
Hey,

We are experiencing connection timeouts and would appreciate more details on how to set the "CONNECTION" timeout.

Currently, we are encountering connection issues to Snowflake via Google Cloud Functions at approximately 12:00 AM every day.

It seems that the function attempts to connect to Snowflake but remains frozen until the GCP function times out.

Running the function again, for example, 8 hours later, works correctly.

**Comment by sfc-gh-dszmolka** [comment]
hi @BartusZak did you try configuring the `timeout` Connection option ? provided a little example snippet just above your comment. Does it not work for you ? (please bear in mind that its value is in `ms` so e.g. for a `30s` timeout you'd need to configure `30000` as a value)

**Comment by BartusZak** [comment]
Hey @sfc-gh-dszmolka ,

Yes, I did, and I thought we are good, but unfortunately it does not work for connection timeout.

```js
  const snowflakeConnection = snowflake.createConnection({
    account: env.SF_ACCOUNT,
    username: env.SF_USERNAME,
    password: env.SF_PASSWORD,
    warehouse: env.SF_DATA_STAGE_WH,
    database: env.SF_DATA_STAGE_DB,
    role: env.SF_DATA_STAGE_ROLE,
    timeout: env.SF_TIMEOUT_IN_MS,
  });
  ...
  
  const connectToSnowflake = async (connection, env) => {
  const maxRetries = env.SF_RETRY_COUNT;
  const timeout = env.SF_RETRY_TIMEOUT_IN_MS;
  let retryCount = 0;

  while (!connection.isUp() && retryCount < maxRetries) {
    try {
      console.info("[Snowflake] Connecting...");
      await new Promise((resolve, reject) =>
        connection.connect((err, conn) => {
          if (err) {
            err.message = `[Snowflake] ${err.message}`;
            reject(err);
          } else {
            console.log(
              `[Snowflake] Successfully connected...`
            );
            resolve(conn);
          }
        })
      );
    } catch (err) {
      console.error(`[Snowflake] Error connecting to Snowflake: ${err}`);
      retryCount++;
      if (retryCount < maxRetries) {
        console.log(`[Snowflake] Retrying in ${timeout} milliseconds...`);
        await delay(timeout);
      } else {
        console.error(
          `[Snowflake] Max retry count reached ${maxRetries}. Connection to Snowflake failed.`
        );
        throw err;
      }
    }
  }

  if (!connection.isUp()) {
    console.error(`[Snowflake] Failed to connect after ${maxRetries} retries.`);
    throw new Error("Failed to connect to Snowflake.");
  }

  return connection;
};
  ```
  
  
![image](https://github.com/snowflakedb/snowflake-connector-nodejs/assets/16143176/779b8e12-ebe5-472b-beeb-d998136b5397)

I can implement a retry on the Google side by changing HTTP triggers to event-driven, but it would involve rewriting the entire flow implemented by the previous developer. However, I'm currently exploring a potential workaround by periodically checking the connection.isUp() using setInterval, but it doesn't function as expected either. 

```js
const checkInitialSfConnection = (connection, env) => {
  console.info("[Snowflake] Checking initial connection ENABLED.");
  let initialConnectionRetries = env.SF_RETRY_COUNT;

  const intervalId = setInterval(() => {
    if (connection) {
      console.info("[Snowflake] Checking connection...");
      if (!connection.isUp()) {
        console.error(
          "[Snowflake] Connection does not exist or timed out. Destroying connection..."
        );
        connection.destroy();

        if (--initialConnectionRetries <= 0) {
          console.info(
            "[Snowflake] Max initial connection retries reached. Exiting..."
          );
          clearInterval(intervalId);
        }
      } else {
        console.info(
          `[Snowflake] Connection is up. connectionId: ${connection.getId()}`
        );
      }
    }
  }, env.SF_TIMEOUT_IN_MS);

  return intervalId;
};
```

I would appreciate any ideas :)

![image](https://github.com/snowflakedb/snowflake-connector-nodejs/assets/16143176/1a4255d8-7942-4c67-8bf9-f420487f05d9)

**Comment by sfc-gh-dszmolka** [comment]
hi @BartusZak thank you for sending all these details! to validate `timeout` connection option, I used this simple script:
```javascript
var snowflake = require('snowflake-sdk');
require('log-timestamp');
console.log('--> Starting up')
console.log(`Node.js process version is: ${process.version}`);

snowflake.configure({
    logLevel: 'trace'
});

console.log('--> Creating Connection')
var connection = snowflake.createConnection({
    account: process.env.SFACCOUNT,
    username: process.env.SFUSER,
    password: process.env.SFPASS,
    warehouse: process.env.SFWH,
    database: process.env.SFDB,
    schema: process.env.SFSCHEMA,
    timeout: 2_000,
    application: __filename.slice(__dirname.length + 1)
});
console.log('--> Connection created')

console.log('--> Connecting to Snowflake')
connection.connect(function(err, conn) {
    if (err) {
        console.error('--> Unable to connect: ' + err.message);
    } else {
        console.log('--> Successfully connected as id: ' + connection.getId());
    }
});

console.log('--> Executing query')
var statement = connection.execute({
    sqlText: 'select \'Query run successfully on Snowflake\' as result;',
    complete: function(err, stmt, rows) {
        if (err) {
            console.error('--> Failed to execute statement due to the following error: ' + err.message);
        } else {
            console.log('--> Query done. [queryID ' + statement.getStatementId() + ', requestId ' + statement.getRequestId() + '] Number of rows produced: ' + rows.length);
            for (row of rows) {
      console.log(row);
      }
        }
    }
});

```

which allows only for 2 second timeout for login. 

Then introduced an artificial 10s delay on the outgoing interface with `tc qdisc add dev eth0 root netem delay 10s` (to disable: `tc qdisc del dev eth0 root netem` ) so login would not be possible within the 2 seconds which `timeout` allows.

Then ran the test script with the following result:
```
# node --no-warnings sfcon.js
[2023-05-30T09:50:30.524Z] --> Starting up
[2023-05-30T09:50:30.526Z] Node.js process version is: v18.16.0
[2023-05-30T09:50:30.526Z] --> Creating Connection
[2023-05-30T09:50:30.529Z] --> Connection created
[2023-05-30T09:50:30.529Z] --> Connecting to Snowflake
{"level":"DEBUG","message":"[9:50:30.5030 AM]: Contacting SF: /session/v1/login-request?requestId=5361a776-1044-47c5-af02-42c78fbf388e&warehouse=COMPUTE_WH&databaseName=TEST_DB&schemaName=PUBLIC, (1/5)"}
[2023-05-30T09:50:30.541Z] --> Executing query
{"level":"DEBUG","message":"[9:50:30.5030 AM]: --createStatementPreExec"}
{"level":"DEBUG","message":"[9:50:30.5030 AM]: numBinds = 0"}
{"level":"DEBUG","message":"[9:50:30.5030 AM]: threshold = 100000"}
{"level":"DEBUG","message":"[9:50:30.5030 AM]: RowStatementPreExec"}
{"level":"DEBUG","message":"[9:50:30.5030 AM]: context.bindStage=undefined"}
{"level":"TRACE","message":"[9:50:30.5030 AM]: https://myaccount.europe-west4.gcp.snowflakecomputing.com/session/v1/login-request?requestId=5361a776-1044-47c5-af02-42c78fbf388e&warehouse=COMPUTE_WH&databaseName=TEST_DB&schemaName=PUBLIC"}
{"level":"DEBUG","message":"[9:50:33.5033 AM]: Contacting SF: /session/v1/login-request?requestId=0cedf7fc-ecd0-4f00-8806-bea720a8ff64&warehouse=COMPUTE_WH&databaseName=TEST_DB&schemaName=PUBLIC, (2/5)"}
{"level":"TRACE","message":"[9:50:33.5033 AM]: https://myaccount.europe-west4.gcp.snowflakecomputing.com/session/v1/login-request?requestId=0cedf7fc-ecd0-4f00-8806-bea720a8ff64&warehouse=COMPUTE_WH&databaseName=TEST_DB&schemaName=PUBLIC"}
{"level":"DEBUG","message":"[9:50:37.5037 AM]: Contacting SF: /session/v1/login-request?requestId=2e979c9e-c895-4ec1-8857-8d31fe53d7a4&warehouse=COMPUTE_WH&databaseName=TEST_DB&schemaName=PUBLIC, (3/5)"}
{"level":"TRACE","message":"[9:50:37.5037 AM]: https://myaccount.europe-west4.gcp.snowflakecomputing.com/session/v1/login-request?requestId=2e979c9e-c895-4ec1-8857-8d31fe53d7a4&warehouse=COMPUTE_WH&databaseName=TEST_DB&schemaName=PUBLIC&clientStartTime=1685440230530&retryCount=2"}
{"level":"DEBUG","message":"[9:50:42.5042 AM]: Contacting SF: /session/v1/login-request?requestId=eb1df242-7666-45e2-825d-4a64d69c382e&warehouse=COMPUTE_WH&databaseName=TEST_DB&schemaName=PUBLIC, (4/5)"}
{"level":"TRACE","message":"[9:50:42.5042 AM]: https://myaccount.europe-west4.gcp.snowflakecomputing.com/session/v1/login-request?requestId=eb1df242-7666-45e2-825d-4a64d69c382e&warehouse=COMPUTE_WH&databaseName=TEST_DB&schemaName=PUBLIC&clientStartTime=1685440230530&retryCount=3"}
{"level":"DEBUG","message":"[9:50:49.5049 AM]: Contacting SF: /session/v1/login-request?requestId=11729c95-f00f-46ac-964d-db8643344db4&warehouse=COMPUTE_WH&databaseName=TEST_DB&schemaName=PUBLIC, (5/5)"}
{"level":"TRACE","message":"[9:50:49.5049 AM]: https://myaccount.europe-west4.gcp.snowflakecomputing.com/session/v1/login-request?requestId=11729c95-f00f-46ac-964d-db8643344db4&warehouse=COMPUTE_WH&databaseName=TEST_DB&schemaName=PUBLIC&clientStartTime=1685440230530&retryCount=4"}
{"level":"DEBUG","message":"[9:50:51.5051 AM]: Failed to all retries to SF."}
[2023-05-30T09:50:51.525Z] --> Unable to connect: Network error. Could not reach Snowflake.
{"level":"DEBUG","message":"[9:50:51.5051 AM]: context.bindStage=undefined"}
{"level":"DEBUG","message":"[9:50:51.5051 AM]: refreshed result of statement with request id = 51e68331-5f10-4310-9a49-217d1646c8aa"}
[2023-05-30T09:50:51.528Z] --> Failed to execute statement due to the following error: Unable to perform operation using terminated connection.
```

We can observe that:
- login indeed times out way less than 10s which is the delay on the `eth0` interface
- actually, times out in ~2s and is retried after that plus some ever-increasing backoff period (1s .. 2s .. etc)
- after 5 retries, the driver gives up and exits

I cannot exactly pinpoint what your program is doing for 500s with the information available above, but I found that the default 5 retry count is also configurable with an undocumented [sfRetryMaxLoginRetries](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/v1.6.20/lib/connection/connection_config.js#L754) option , which when set to 2 as a test:
```javascript
var connection = snowflake.createConnection({
    account: process.env.SFACCOUNT,
..
    timeout: 2_000,
    sfRetryMaxLoginRetries: 2
});
```

resulting the above test script failing faster in the 10s-delay scenario (only tried login 2 times instead of 5). 

So for now for me, it looks like the `timeout` option in the `Connection` options seems to be working as intended , of course setting it so low might not be an option in every case (this was just a test case) since it seems to influence the generic [HTTP request timeout](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/v1.6.20/lib/http/base.js#L74). So perhaps tinkering with `sfRetryMaxLoginRetries` might be a better way to fail faster.  
Hope this helps somewhat, but of course optimally it would be nice to find the root cause of that thing blocking the connectivity in the first place.

**Comment by BartusZak** [comment]
Hey @sfc-gh-dszmolka 

I have been testing your approach on our development environment, and it seems that our DEV env IP address has been blacklisted by Snowflake.

```
 [Snowflake] Connecting...
 [Snowflake] Successfully connected.
 ```

Although my code can establish a connection to Snowflake, when I run queries, it returns an error stating that Snowflake is not available. Initially, I thought I might have been timed out and needed to wait for 24 hours, but it has been over a week now and the issue persists.

```
[Snowflake] Running query on Snowflake...
[Snowflake] Disconnecting...
[Snowflake] Network error. Could not reach Snowflake.
GCP cloud-function failed.
Function execution took 375106 ms, finished with status: 'error'
```

To troubleshoot, I redeployed the same code on a different environment with a different IP address, or I run the code from my local environment, and everything works fine.

I would greatly appreciate your assistance in resolving this issue. 

Thank you.

**Comment by sfc-gh-dszmolka** [comment]
hi @BartusZak I can assure you Snowflake does not 'blacklist' IP addresses. Customer have the option to blacklist some IP/CIDR themselves with network policies, but I guess you would know about that if it was implemented. Also the error message is quite clear in that case, IP X.X.X.X is not allowed to access snowflake.

Not really sure from what you drew the conclusion the IP is blacklisted, but I believe the reason for 'Network error' is something different. I can help and confirm if you can send the request_id of the login-request (should be available in the logs) to confirm if it reached Snowflake at all, and what happened.

You might want to work with [Snowflake Support in a support case](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) if you're not comfortable sharing with these details here. 

But since you mentioned it works on a different environment, maybe it's the environment itself or its configuration which has the problem ? Perhaps you could also consider involving GCP Support to help you debug the GCP part.

**Comment by markandrus** [comment]
Hi @sfc-gh-dszmolka, unfortunately, the `timeout` setting does not work.

You can confirm it does not work with the following `test.js` file:

```js
// test.js

const snowflake = require('.') // or require('snowflake-sdk')

console.log('>>>', new Date().toISOString(), 'snowflake.createConnection')
const connection = snowflake.createConnection({
  account: 'does-not-exist',
  database: 'bogus',
  password: 'bogus',
  role: 'bogus',
  schema: 'bogus',
  username: 'bogus',
  warehouse: 'bogus',
  timeout: 1
})

connection.connect(err => {
  console.error('>>>', new Date().toISOString(), 'connection.connect', err)
})
```

Notice I've set a non-existant `account` ("does-not-exist"), and I've set the `timeout` to be 1 ms. I could set 10 ms, 100 ms, it doesn't matter. Every time it takes snowflake-sdk about **three minutes** to timeout:

```
$ node test.js
>>> 2024-03-14T12:09:07.253Z snowflake.createConnection
>>> 2024-03-14T12:11:57.581Z connection.connect Error [NetworkError]: Network error. Could not reach Snowflake.
    at createError (/Users/mark/src/mark/snowflake-connector-nodejs/lib/errors.js:527:17)
    at exports.createNetworkError (/Users/mark/src/mark/snowflake-connector-nodejs/lib/errors.js:279:10)
    at Object.callback (/Users/mark/src/mark/snowflake-connector-nodejs/lib/services/sf.js:572:26)
    at /Users/mark/src/mark/snowflake-connector-nodejs/lib/http/base.js:47:19
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7) {
  code: 401001,
  cause: AxiosError: timeout of 1ms exceeded
```

Confusingly, the error's `cause` does mention "AxiosError: timeout of 1ms exceeded", but we waited 50 s…

It seems like the parameters defined here should be exposed: https://github.com/snowflakedb/snowflake-connector-nodejs/blob/master/lib/connection/connection_config.js#L843-L855

**Comment by sfc-gh-dszmolka** [comment]
hi @markandrus thanks for the mention - do you think it would be possible to create a new issue so we could track it properly? thank you in advance if this is possible!
