### ISSUE TITLE
Query large records crashes the sdk.

### ISSUE THREAD

**Issue by surajkrishan** [snowflakedb/snowflake-connector-nodejs#248]
node v12.9.1
npm 6.10.2

Hi team, 

i am trying to query large records from snowfalke sdk, i am using latest version of sdk & total no. of records are 1.8 million. 
But after quering these many records the sdk gets crashed. 

SQL STMT : SELECT DISTINCT ABC FROM XYZTABLE;

Thanks,
Suraj

**Comment by sfc-gh-wfateem** [comment]
Hi @surajkrishan,

Were there any errors that you can share?

Can you maybe paste the code you're using to query Snowflake? 

Just an idea, have you tried using pm2 to monitor your NodeJS process to observe what the memory consumption looked like before the crash?
[PM2](https://www.npmjs.com/package/pm2)

**Comment by sfc-gh-wfateem** [comment]
Hi @surajkrishan,

I'm going to close this off since we haven't heard back from you. Feel free to come back to us if you have more information that you can share about this particular problem.
