### ISSUE TITLE
Script to run tests appears to be missing?

### ISSUE THREAD

**Issue by dylangrandmont** [snowflakedb/snowflake-connector-nodejs#249]
When I clone this repo locally and attempt to run its test suite, I find that `npm test` is looking for a file `./scripts/run_test.sh`; however this script is not checked into source code on the master branch. Is this intended?

I was hoping to run these tests as a sanity check before submitting a PR into this library.

Best,

**Comment by sfc-gh-wfateem** [comment]
Recreate jira

**Comment by sfc-gh-wfateem** [comment]
Hi @dylangrandmont 

This [PR](https://github.com/snowflakedb/snowflake-connector-nodejs/pull/270) should have fixed this now.
