### ISSUE TITLE
Support for GET/PUT commands

### ISSUE THREAD

**Issue by iamEAP** [snowflakedb/snowflake-connector-nodejs#25]
I am looking to push and pull large datasets into and out of Snowflake using this node.js SDK.  I noticed in [the documentation](https://docs.snowflake.net/manuals/user-guide/nodejs-driver-use.html) that `GET` and `PUT` are not currently supported in node.js.

I was wondering when this might be available.  In an ideal world, I could issue a `GET` command and have a `Readable` stream returned.  Likewise, I'd love to use `Writeable` stream for `PUT`'ing data to Snowflake.

It's not ideal, but as a workaround, I am planning on spawning child processes of `SnowSQL` (CLI) from node and reading/writing to/from the local file system.

**Comment by smtakeda** [comment]
PUT and GET support for NodeJS driver is in the plan but not in the short term. In fact, it is not easy to patch quickly. Please raise a request to the Snowflake support.

**Comment by flashtheman** [comment]
Is there already a roadmap for this feature?

**Comment by thunter05** [comment]
@smtakeda is there any way to move this up the priority list (and get some committment on a timeline)? We are having to build our apps to wrap nodejs logic around the snowflake python driver to pull this off. Works ok but feels pretty clunky long-term. Our organization is kind of stumped as to why the NodeJs driver would not support feature this by now.

**Comment by sfc-gh-dszmolka** [comment]
`PUT` implemented with v1.6.2, `GET` implemented with v1.6.6, thank you everyone for your patience!
