### ISSUE TITLE
`host` is not properly defined which makes the package unusable in strict mode applications

### ISSUE THREAD

**Issue by Amit-Popcorn** [snowflakedb/snowflake-connector-nodejs#252]
https://github.com/snowflakedb/snowflake-connector-nodejs/blob/cc402a83190749910a45a21f655d48c9a9837b74/lib/util.js#L472

**Comment by sfc-gh-dszmolka** [comment]
thank you for raising this issue. it seems to be fixed with #277 which is released with `v1.6.9`, thus closing this issue. if it's still an issue for you, please feel free to reopen.
