### ISSUE TITLE
SNOW-555164: Security vulnerability in requestretry 6.0.0

### ISSUE THREAD

**Issue by donhcd** [snowflakedb/snowflake-connector-nodejs#268]
https://github.com/snowflakedb/snowflake-connector-nodejs/blob/master/package.json#L36
https://huntr.dev/bounties/a779faf5-c2cc-48be-a31d-4ddfac357afc/

This is fixed in 7.0.0, but the package.json for this repo specifies ^6.0.0. Are there plans to upgrade this dependency soon?

**Comment by sfc-gh-hchaturvedi** [comment]
@SimbaGithub can we please prioritize this for the next driver release? Thanks.

**Comment by duki994** [comment]
@sfc-gh-hchaturvedi 

I have tried using `npm-force-resolutions` to force `requestretry` version to ^7.0.0;

Here is relevant 'TRACE' log of `snowflake-sdk` with sensitive information hidden:

> {"level":"DEBUG","message":"[10:45:11.4511 AM]: Contacting SF: /session/v1/login-request?requestId={*HIDDEN*}&databaseName={*HIDDEN*}&schemaName={*HIDDEN*}, (1/5)"}
{"level":"TRACE","message":"[10:45:15.4515 AM]: https://{*hidden accountId*}.us-east-1.snowflakecomputing.com/session/v1/login-request?requestId={*HIDDEN*}&databaseName={*HIDDEN*}&schemaName={*HIDDEN*}"}
{"level":"DEBUG","message":"[10:45:15.4515 AM]: Reading OCSP cache file. /home/dusank/.cache/snowflake/ocsp_response_cache.json"}
{"level":"TRACE","message":"[10:45:15.4515 AM]: Returning OCSP status for certificate {*HIDDEN*} from cache"}
{"level":"TRACE","message":"[10:45:15.4515 AM]: Returning OCSP status for certificate {*HIDDEN*} from cache"}
{"level":"TRACE","message":"[10:45:15.4515 AM]: Returning OCSP status for certificate {*HIDDEN*} from cache"}
{"level":"TRACE","message":"[10:45:15.4515 AM]: Returning OCSP status for certificate {*HIDDEN*} from cache"}
{"level":"TRACE","message":"[10:45:15.4515 AM]: socket reused = false"}
{"level":"TRACE","message":"[10:45:15.4515 AM]: OCSP validation succeeded for {*HIDDEN*}.us-east-1.snowflakecomputing.com"}
{"level":"TRACE","message":"[10:45:19.4519 AM]: https://{*hidden account id*}.us-east-1.snowflakecomputing.com/queries/v1/query-request?requestId={*HIDDEN*}"}
{"level":"DEBUG","message":"[10:45:20.4520 AM]: HTTP Error: 401"}



I also took step to console.log error happening in this line of `sf.js`: 
https://github.com/snowflakedb/snowflake-connector-nodejs/blob/b1815c37c5a9e2aaf45159e28f0e84c338a24350/lib/services/sf.js#L606


This is relevant output of console.log on body parameter:
```
 body: '{\n' +
    '  "data" : null,\n' +
    '  "code" : "390103",\n' +
    '  "message" : "Session token not found in the request data.",\n' +
    '  "success" : false,\n' +
    '  "headers" : null\n' +
    '}',

```

I don't know what error code 390103 means and can't find it on Snowflake docs.
As I see this is some SAML / OAuth error.
There is Authorization header with "Snowflake Token={something}" sent. So I think this session token is something else.


@sfc-gh-hchaturvedi 
I hope this info of me trying to use requestretry ^7.0.0 will help you in actually integrating it in next sdk release :)

**Comment by duki994** [comment]
`requestretry` version `7.0.0` has this problem
https://github.com/FGRibreau/node-request-retry/issues/140

That's what gave me error 390103 (explained in comment above).

Versions `7.0.1` and `7.0.2` work good

**Comment by pedrokohler** [comment]
Any news regarding this issue? Are we planning on updating the dependency?

**Comment by sfc-gh-dszmolka** [comment]
should be already resolved since https://github.com/snowflakedb/snowflake-connector-nodejs/pull/278 which removed this dependency (which requestretry was anyways updated to non-vulnerable version earlier but it's obsoleted now)

**Comment by sfc-gh-dszmolka** [comment]
closing, see above comment
