### ISSUE TITLE
SNOW-560911: Unused dependencies as of v1.6.7

### ISSUE THREAD

**Issue by veltman** [snowflakedb/snowflake-connector-nodejs#275]
The package.json for the Snowflake connector includes a large number of `dependencies` and `devDependencies` that don't appear to be used anywhere in the codebase or necessary as peerDependencies:

```
http-signature
https-proxy-agent
json-schema
jsprim
lodash
oscp
follow-redirects
insert-module-globals
vinyl-buffer
vinyl-source-stream
```

Is there a reason why these dependencies are still required?

Additionally, these two packages are listed in `dependencies` but are only used in tests, so seem like they should be in `devDependencies`:
```
mock-require
test-console
```

**Comment by kirillgroshkov** [comment]
Yes, I double that. We pinned `snowflake-sdk` to `1.6.1` long time ago to avoid unnecessary dependency bloat.

**Comment by sfc-gh-dszmolka** [comment]
should be fixed by linked PR, closing issue
