### ISSUE TITLE
SNOW-565105: Vulnerability in "request" library

### ISSUE THREAD

**Issue by bobbrodie** [snowflakedb/snowflake-connector-nodejs#281]
The `snowflake-sdk` package is dependent on `request@2.88.2`, which is problematic because:
1. The `request` library is deprecated
2. The `request` library uses `qs@6.5.3` defined by `~6.5.3`
3. The version of qs cannot be overridden with a patched version using npm overrides because it will throw a version mismatch

-----

1. What version of NodeJS are you using (`node --version` and `npm --version`)? 
```
node: v16.13.2
npm: 8.5.5
```

4. What operating system and processor architecture are you using?
```
Software:

    System Software Overview:

      System Version: macOS 12.3 (21E230)
      Kernel Version: Darwin 21.4.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Robert’s MacBook Pro (2)
      User Name: Robert Brodie (r.brodie)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 11 days 5:17
```

5. What are the component versions in the environment (`npm list`)?
**Not applicable**

6. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
```
npm ls qs
```

7. What did you expect to see?
```
A version greater than 6.8.0
```

8. What did you see instead?
```
└─┬ snowflake-sdk@1.5.2
  └─┬ request@2.88.2
    └── qs@6.5.3
```

9. Add this to get standard output.
**Not applicable**

**Comment by fhawkes** [comment]
Yeah we've got this on our radar a well. We've actually moved to axios because the request lib expose a CVE, but obviously the fact that this is one of our deps means we're still going to be pulling in request.

**Comment by sfc-gh-dszmolka** [comment]
`request`   removed from dependencies with `v1.6.12`, closing this issue
