### ISSUE TITLE
SNOW-572563: Types issue with `connection.execute` requiring argument `complete` 

### ISSUE THREAD

**Issue by asafpelegcodes** [snowflakedb/snowflake-connector-nodejs#287]
Please answer these questions before submitting your issue. Thanks!

1. What version of NodeJS are you using (`node --version` and `npm --version`)?
node: v16.14.2 
npm: 8.5.0
2. What operating system and processor architecture are you using?
MacOS Big Sur (intel chip)

3. What are the component versions in the environment (`npm list`)?
├── @types/node@17.0.23
├── @types/snowflake-sdk@1.6.2
├── @typescript-eslint/eslint-plugin@5.18.0
├── @typescript-eslint/parser@5.18.0
├── dotenv@16.0.0
├── eslint-plugin-jest@26.1.4
├── eslint-plugin-prettierx@0.18.0
├── eslint@8.12.0
├── lint-staged@12.3.7
├── prettierx@0.19.0
├── snowflake-sdk@1.6.8
├── ts-node-dev@1.1.8
└── typescript@4.6.3

4. What did you do?
```
import { createConnection } from 'snowflake-sdk'

const connection = createConnection({
  account: account,
  password: password,
  username: username,
  warehouse: warehouse
})
connection.connect(function (err, conn) {
  if (err) console.log('broken', err)
})

const statement = connection.execute({
  sqlText: 'select * from table'
})
```

5. What did you expect to see?
That it doesn't error when being compiled and I can provide just a sql query.  According to the documentation [here](https://docs.snowflake.com/en/user-guide/nodejs-driver-use.html#) it should be possible. However, the types for the sdk do not allow it since it will not be compiled properly. 

6. What did you see instead?
> Argument of type '{ sqlText: string; }' is not assignable to parameter of type '{ sqlText: string; streamResult?: boolean; binds?: Binds; fetchAsString?: ("String" | "Boolean" | "Number" | "Date" | "JSON")[]; complete: (err: SnowflakeError, stmt: Statement, rows: any[]) => void; }'.
  Property 'complete' is missing in type '{ sqlText: string; }' but required in type '{ sqlText: string; streamResult?: boolean; binds?: Binds; fetchAsString?: ("String" | "Boolean" | "Number" | "Date" | "JSON")[]; complete: (err: SnowflakeError, stmt: Statement, rows: any[]) => void; }'.

**Comment by briangottfried** [comment]
This is fixed with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60545.

**Comment by sfc-gh-dszmolka** [comment]
hi, thank you for submitting this issue. i see this was fixed in the types long ago, so marking this issue as closed. if you still feel you need assistance with it, please reopen with the details. thank you !
