### ISSUE TITLE
SNOW-595248: Port the library to TypeScript (phase1: add typing)

### ISSUE THREAD

**Issue by varun-dc** [snowflakedb/snowflake-connector-nodejs#309]
This library is written in a old style JavaScript manner. While this is functional for the most part, it would be more maintainable if it was written in a well typed language like TypeScript that would allow better type checking, preventing bugs like https://github.com/snowflakedb/snowflake-connector-nodejs/issues/308 (which occurred because of a type mismatch related error)

The library would also be easier for outside contributors to understand as well if they could lean on the TypeScript compiler and associated tooling to navigate and understand the code.

**Comment by kri5t** [comment]
I completely agree. I was trying to make sense of this library to add functionality of uploading a file from a stream instead of the hard-coded file path upload that is supported. But I gave up because the library was too much a mess.

**Comment by sfc-gh-anugupta** [comment]
We plan to add the support for Typescript support, and it's in our backlog. I dont have any ETA yet, but we will prioritize it as we do the next quarter planning. We will keep this thread updated. 

Thanks all for your patience.

**Comment by sfc-gh-dszmolka** [comment]
Hi everyone - it's been a while but I have some progress to report. We're actively working on adding the typing for `snowflake-sdk` and then going forward, maintaining it which will allow us to release the changes to the typing alongside with the changes of the driver, if any. Thus hopefully preventing the discrepancy between the changes to the driver library vs. the externally maintained typing lagging behind.  

Rewriting the whole library in TypeScript is another story though, I don't have any estimation for that, but the types are coming soon.

**Comment by sfc-gh-dszmolka** [comment]
PR https://github.com/snowflakedb/snowflake-connector-nodejs/pull/762 has been merged now, and will be released with the next release cycle, towards end of May 2024

**Comment by sfc-gh-dszmolka** [comment]
released with May 2024 release cycle, version 1.11.0. thank you for your patience here !

**Note**: if the externally maintained typings might be conflicting now with the Snowflake-internal ones, please try to uninstall the external one / remove it from the dependencies. Also if there are unexpected issues with the typings, do raise a new issue please.

For rewriting and porting the whole library to TypeScript, there is no plans for the foreseeable future.
