### ISSUE TITLE
SNOW-610601: Unable to alter session variable to dynamic value by binding.

### ISSUE THREAD

**Issue by ksze** [snowflakedb/snowflake-connector-nodejs#315]
Please answer these questions before submitting your issue. Thanks!

1. What version of NodeJS are you using (`node --version` and `npm --version`)?

node v16.15.1
npm 8.12.1

2. What operating system and processor architecture are you using?

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

3. What are the component versions in the environment (`npm list`)?

&lt;censored&gt;@1.0.0 /home/kal/git/&lt;censored&gt;
├── @azure/event-hubs@5.8.0
├── @azure/eventhubs-checkpointstore-blob@1.0.1
├── @azure/storage-blob@12.10.0
├── @babel/preset-env@7.18.2
├── @babel/preset-typescript@7.17.12
├── @shopify/eslint-plugin@41.2.1
├── @types/async-retry@1.4.4
├── @types/chai@4.3.1
├── @types/cors@2.8.12
├── @types/express@4.17.13
├── @types/lodash@4.14.182
├── @types/luxon@2.3.2
├── @types/mocha@9.1.1
├── @types/node@16.11.36
├── @types/snowflake-sdk@1.6.7
├── @types/swagger-ui-express@4.1.3
├── @types/yamljs@0.2.31
├── @typescript-eslint/eslint-plugin@5.26.0
├── @typescript-eslint/parser@5.26.0
├── async-retry@1.3.3
├── axios@0.27.2
├── chai-http@4.3.0
├── chai@4.3.6
├── cors@2.8.5
├── dotenv-safe@8.2.0
├── eslint@8.16.0
├── express@4.18.1
├── fp-ts@2.12.1
├── husky@8.0.1
├── io-ts@2.2.16
├── lint-staged@12.4.2
├── lodash@4.17.21
├── luxon@2.4.0
├── mocha-junit-reporter@2.0.2
├── mocha@10.0.0
├── mysql2@2.3.3
├── nodemon@2.0.16
├── reflect-metadata@0.1.13
├── sequelize@6.20.0
├── snowflake-sdk@1.6.10
├── swagger-cli@4.0.4
├── swagger-ui-express@4.4.0
├── ts-node@10.8.0
├── typescript@4.7.2
├── winston@3.7.2
└── yamljs@0.3.0

4. What did you do?

```typescript
/* eslint-disable no-console */
// Load the Snowflake Node.js driver.
import snowflake from 'snowflake-sdk';
import { DateTime } from 'luxon';

import { env } from './src/infrastructure/env';

// Create the connection pool instance
const connectionPool = snowflake.createPool(
  {
    account: env.SNOWFLAKE_ACCOUNT,
    username: env.SNOWFLAKE_USERNAME,
    password: env.SNOWFLAKE_PASSWORD,
    warehouse: env.SNOWFLAKE_WAREHOUSE,
    database: env.SNOWFLAKE_DATABASE,
    application: env.SNOWFLAKE_APPLICATION,
    role: env.SNOWFLAKE_ROLE,
  },
  // pool options
  {
    max: 10, // specifies the maximum number of connections in the pool
    min: 0, // specifies the minimum number of connections in the pool
  },
);

// Use the connection pool and execute a statement
// eslint-disable-next-line @typescript-eslint/no-floating-promises
connectionPool.use(async (clientConnection) => {
  // This has no effect.
  await clientConnection.execute({
    sqlText: "ALTER SESSION SET TIMEZONE = :1;",
    binds: ['Asia/Tokyo'],
  });

  /**
   * The TypeScript engine may indicate that the `await` is unnecessary, but it is actually a bug in the
   * @types/snowflake-sdk package. You *need* the `await`.
   */
  // Execute SELECT statement; FCS_DATETIME is a TIMESTAMP_LTZ
  const statement = await clientConnection.execute({
    sqlText: 'select FCS_DATETIME from my_db.my_schema.my_table;',
  });
  const stream = statement.streamRows();

  /**
   * The official Snowflake documentation describes two ways of accessing the data stream, both rely on the `.on()`
   * handler, which is clumsy and unwieldy.
   * Fortunately, because `stream` is actually a Node.js `internal.Readable`, we can use async iteration instead.
   */
  let i = 0;
  for await (const row of stream) {
    console.log(row.FCS_DATETIME.getTimezone());  // This still return 'America/Los_Angeles'
    console.log(DateTime.fromJSDate(row.FCS_DATETIME, { zone: row.FCS_DATETIME.getTimezone() }).toISO()); // This still prints the date-time in America/Los_Angeles timezone.
    i += 1;
    if (i === 2) { break; }
  }
});

```

5. What did you expect to see?
The timezone of the sessions should be changed to 'Asia/Tokyo' and the date-times should be returned in 'Asia/Tokyo' timezone. For example:
```
Asia/Tokyo
2022-06-09T12:00:00.000+09:00
Asia/Tokyo
2022-06-09T12:30:00.000+09:00
```

6. What did you see instead?
The date-times are still returned in 'America/Los_Angeles' timezone:
```
America/Los_Angeles
2022-06-08T20:00:00.000-07:00
America/Los_Angeles
2022-06-08T20:30:00.000-07:00
```

Note that in order to produce the output in 5., I had to hard-code the timezone name in the SQL directly, instead of binding.

**Comment by sfc-gh-dprzybysz** [comment]
This behaviour seams to be currently not supported by Snowflake.
When you set logging level to `TRACE`
```
snowflake.configure({
    logLevel: "TRACE",
});
```
There will be error:
```
Error thrown during execution: {"name":"OperationFailedError","code":"001003","message":"SQL compilation error:\nBind variables are currently unsupported in parameter values","sqlState":"42000","data":{"internalError":false,"errorCode":"001003","age":0,"sqlState":"42000","queryId":"01ac89cc-0100-0001-0000-00000018ac39","line":-1,"pos":-1,"type":"COMPILATION"}
```

**Comment by sfc-gh-dszmolka** [comment]
this feature as it turns out, is not supported on the Snowflake backend. At this moment there's no timeline available when the server-side support will be available. Therefore, closing this issue for now.

Internally, we're tracking this request and can reopen again if and when the server-side support will be implemented.
