### ISSUE TITLE
SNOW-616705: Date.toJSON() doesn't return expected date string

### ISSUE THREAD

**Issue by ZeRego** [snowflakedb/snowflake-connector-nodejs#317]
Please answer these questions before submitting your issue. Thanks!

1. What version of NodeJS are you using (`node --version` and `npm --version`)?

v14.17.5

2. What operating system and processor architecture are you using?

System Version: macOS 12.4 (21F79)
Kernel Version: Darwin 21.5.0

3. What are the component versions in the environment (`npm list`)?

"snowflake-sdk": "^1.6.4",

5. What did you do?

Fetch data from snowflake where there is a column of type TIMESTAMP_NTZ(9).
The values for that column are of type Date but the method toJSON() doesn't return the expected value.

6. What did you expect to see?

```
value.toJSON(); // returns "2017-02-11T03:00:00.000Z"
```

7. What did you see instead?

```
value.toJSON(); // returns "2017-02-11 03:00:00.000"
```

**Comment by sfc-gh-wshangguan** [comment]
Hi @ZeRego , Snowflake timestamp has many different output formats as stated https://docs.snowflake.com/en/user-guide/date-time-input-output.html#timestamp-formats. I think the one you saw is just one of them. And I was wondering maybe use different timestamp output format can help. Have you tried this was before?

**Comment by sfc-gh-wshangguan** [comment]
Hi @ZeRego , 
> Is it possible to set the desired format when create a connection, via ConnectionOptions or when we execute sql ?

So your application manages the connection (or we call it a session) for users? If so, it seems like [altering the parameter at session level](https://docs.snowflake.com/en/sql-reference/sql/alter-session.html) can be an option. The setting of a parameter at session level only lives within this single connection. Once the connection is closed, the settings just go away. And it won't impact any other level settings of the users.

**Comment by sfc-gh-dszmolka** [comment]
hi @ZeRego been reviewing some issues and stumbled across this one. seems there's been already an answer. do you think this issue can be closed or do you require any further assistance with it ?

**Comment by sfc-gh-dszmolka** [comment]
closing this issue for now, but please reopen if you still need help
