### ISSUE TITLE
SNOW-617206: Missing project description in npm pacakge repository 

### ISSUE THREAD

**Issue by sfc-gh-kbregula** [snowflakedb/snowflake-connector-nodejs#318]
Hi.

Our library in the npm repository has no description, which looks [very unprofessional](https://www.youtube.com/watch?v=3t6L-FlfeaI).
<img width="1792" alt="Screenshot 2022-06-23 at 10 16 47" src="https://user-images.githubusercontent.com/78743291/175251122-c347bc94-0e85-4f22-bb4f-6f88e4de6194.png">
It would be good to add the correct package description and documentation references.

Best regards,
Kamil

**Comment by sfc-gh-dszmolka** [comment]
resolved by https://github.com/snowflakedb/snowflake-connector-nodejs/pull/326

**Comment by sfc-gh-dszmolka** [comment]
see previous comment, closing
