### ISSUE TITLE
Support authenticator parameter for SSO and browser based auth

### ISSUE THREAD

**Issue by mike-seekwell** [snowflakedb/snowflake-connector-nodejs#32]
[See Python implementation here](https://github.com/snowflakedb/snowflake-connector-python/search?q=authenticator&unscoped_q=authenticator) and [here](https://docs.snowflake.net/manuals/user-guide/python-connector-example.html#connecting-using-federated-authentication)

**Comment by buffolander** [comment]
any word on having authenticator in Node.js?

**Comment by nataliiapreston-bc** [comment]
> any word on having authenticator in Node.js?

What are the alternative authentication methods for Node.js besides username and password? Is the SSO for Node.js in the plans?

**Comment by udalovas** [comment]
> Is the SSO for Node.js in the plans?

Looks like the demand is acknowledged, though with no specific timeline set to it: https://github.com/snowflakedb/snowflake-connector-nodejs/issues/111

**Comment by RichieRunner** [comment]
Took me 2 days of research into why my SSO creds weren't working with this driver to finally land here 🙂
Time to use another language driver I guess.

**Comment by RichieRunner** [comment]
Just tried the .NET connector, and found that that [the connector over there does not work either](https://github.com/snowflakedb/snowflake-connector-net/issues/259).

So when it comes to SSO authenticator, NodeJs and C# cannot be used.

Does anybody still work here?

**Comment by sfc-gh-kwagner** [comment]
External browser auth support should be released within the next two releases

**Comment by sfc-gh-dszmolka** [comment]
external browser authentication support released with v1.6.0, thank you for your patience
