### ISSUE TITLE
SNOW-620316: What's the status of this library? All issues were just closed without any reason or update from the team

### ISSUE THREAD

**Issue by varun-dc** [snowflakedb/snowflake-connector-nodejs#322]
All the issues on this repo were closed without any news or update or reason.
The issues included a number of valid bugs.

Can we have an update about the status of this library? It doesn't seem like it's getting much attention from the Snowflake team for a long time now.

**Comment by albertyfwu** [comment]
There are also a bunch of features missing (compared to the V2 SQL API). Is there any intention of implementing these? For example, https://github.com/snowflakedb/snowflake-connector-nodejs/issues/331

From what I see on the Pull Requests, the only ones approved and merged are by Snowflake team members.

Could we get more clarity, please?

**Comment by manvydasu** [comment]
@sfc-gh-kdama @SimbaGithub 
Would it be possible to get answer on this?

There are some legit issues which prevent application from being used in production apps (i.e. https://github.com/snowflakedb/snowflake-connector-nodejs/issues/336).

**Comment by APTy** [comment]
Is there anyone who can provide some response on the status of this project? Maybe @jdanielmyers?

At the very least, it's reasonable to provide Snowflake's customers with an expectation of the level of support for this library. Something like: "This is beta software and shouldn't be depended on in production," if that's the case.

As of this writing, here are my observations of the project:
- There are 13+ open PRs that are more than 6 moths old.
- There are numerous open issues that have actually been resolved, but the issues haven't been closed.
- There are production features and bugs that have been not been resolved for **3+ years**:
  - #67 
  - #68 
- Community contributions (PRs, issues) often take weeks to receive responses, if any.
- The repo has no `CONTRIBUTING.md` or `CODEOWNERS` files to indicate how the community should interact with the project.
- The JIRA integration that creates tickets based on github issues is currently [broken](https://github.com/snowflakedb/snowflake-connector-nodejs/pull/388).
- CI tests on master currently appear to be [broken](https://github.com/snowflakedb/snowflake-connector-nodejs/actions/runs/3766143192/jobs/6467519645).

There are many in the Snowflake community (like myself) who are willing and able to support the project, but it would be helpful to get some guidance on what we should expect from the project and its maintainers.

Thanks!

**Comment by sfc-gh-anugupta** [comment]
We are actively working to  provide better support to community issues and PRs across all Snowflake SDKs/Drivers .   Please  do note for any production related issue , the best way to reach out us is via our snowflake support channel.

**Comment by sfc-gh-dszmolka** [comment]
closing this issue for now. the response to the original 'why were all issues just closed' is due to a badly implemented change for github actions i believe, which was rectified long ago and the issues reopened. btw if you see your issues was closed by this action last year, is still valid, and was not reopened - please do reopen it.

**Comment by datbth** [comment]
hi @sfc-gh-dszmolka, I don't have the "Re-open Issue" button available on my side.  
![image](https://user-images.githubusercontent.com/15865062/221130593-9f8e83b7-692d-49c1-bcc8-1a7636fbff46.png)


Shall I copy [my issue](https://github.com/snowflakedb/snowflake-connector-nodejs/issues/176)'s contents into a new one?

**Comment by sfc-gh-dszmolka** [comment]
hi @datbth - thank you, reopened #176 for you and will take a look once I get there
