### ISSUE TITLE
Remove extra newline from private key check

### ISSUE THREAD

**Issue by CJxD** [snowflakedb/snowflake-connector-nodejs#335]
4. What did you do?
Didn't have an extra newline in my private key in my credentials.

5. What did you expect to see?
It not to matter.

7. What did you see instead?

`InvalidParameterError: Invalid private key. The specified value must be a string in pem format of type pkcs8`

This took a lot of debugging to check if the key encryption was OK and the format could be read by OpenSSL, but it turned out to just be the lack of a newline.

The culprit is `isPrivateKey` in lib/utils.js

https://github.com/snowflakedb/snowflake-connector-nodejs/blob/5bd5c131545491b1698ef7b7e7c70219c8e67242/lib/util.js#L153-L158

which requires a newline at the end, and I can't imagine why it's necessary.

You've already got a regex based private key detector here

https://github.com/snowflakedb/snowflake-connector-nodejs/blob/7b3eaa9acb0859a57ecac399766dc9fb84a24b58/lib/secret_detector.js#L72

**Comment by sfc-gh-dszmolka** [comment]
hi, thank you for submitting this issue and pinpointing where it happens. Checked and it seems that both the `privateKey` and `privateKeyPath` methods for keypair authentication are working well as described in [Snowflake documentation for Using Key Pair Authentication & Key Pair Rotation](https://docs.snowflake.com/en/user-guide/nodejs-driver-use.html#using-key-pair-authentication-key-pair-rotation).

however if one would paste the private key as a literal and try to use that with `privateKey`, it indeed breaks with the aforementioned error - until the newline character is introduced at the end of the key's footer, that is. we'll look into this and see if the private key detection could be made a bit more resilient.

**Comment by CJxD** [comment]
Thanks David :)

**Comment by sfc-gh-dszmolka** [comment]
#566

**Comment by sfc-gh-dszmolka** [comment]
PR is now merged and will be part of the next release; expected towards end of July

**Comment by sfc-gh-dszmolka** [comment]
PR is released as part of the latest Snowflake Node.JS driver version 1.7.0. Closing this issue.

**Comment by sfc-gh-dszmolka** [comment]
Releng team hit a bump in the release process which will be continued on Monday as expected. Reopening the issue and will only close when artifact confirmed to published to npm. Apologies for the inconvenience.

**Comment by sfc-gh-dszmolka** [comment]
PR is released as part of the latest Snowflake Node.JS driver version 1.7.0, for real this time :) Visible on `npm` too. Closing this issue and thank you for bearing with us !
