### ISSUE TITLE
https-proxy-agent module not found

### ISSUE THREAD

**Issue by bibli-alex** [snowflakedb/snowflake-connector-nodejs#343]
[This PR](https://github.com/snowflakedb/snowflake-connector-nodejs/pull/276) removed `https-proxy-agent` from the list of dependencies. You still require it within the `https_proxy_ocsp_agent.js` file at [this line](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/f10ef25195d092f3324f6bdfb9cca127ffc52e00/lib/agent/https_proxy_ocsp_agent.js#L13)

This causes dependency issues.

**Comment by mscott5861** [comment]
I'm seeing this issue as well.

**Comment by MattCorwin** [comment]
Same here

**Comment by sfc-gh-dszmolka** [comment]
thank you for reporting this issue. #293 and #343 look similar, in a way that both of them are caused by the missing dependencies. seems to be still missing in the latest version of the driver (1.6.17 now), we'll take a look.

**Comment by sfc-gh-dszmolka** [comment]
#482

**Comment by sfc-gh-dszmolka** [comment]
fix released with version [1.6.22](https://github.com/snowflakedb/snowflake-connector-nodejs/releases/tag/v1.6.22)
