### ISSUE TITLE
Node: How to get data as global variable

### ISSUE THREAD

**Issue by alakdam07** [snowflakedb/snowflake-connector-nodejs#348]
I have datas in [snowflake](https://www.snowflake.com/en/), I am planning to retrieve datas from two diffrent databases. For connectiing in snowflake, I used [snowflake-sdk](https://www.npmjs.com/package/snowflake-sdk) package. I successfully connect to database. I can also successfully able to query both data. 

I am having issue to combine both data and return them as an object. Because whenever, I put the variables out of snowflake `complete` function and rerun the query, it always return empty object.

**My goal is to combine both of global variable object.**

    const connection = createConnection({
      account: 'database',
      username: 'john',
      database: 'database',
      authenticator: 'SNOWFLAKE_JWT',
      privateKey, // RSA Key
    })

    connection.connect(function (err: unknown, conn: unknown) {
      if (err) {
        console.error('Unable to connect: ' + err.message)
        console.error('Unable to connect: ' + conn.getId())
      } else {
        console.log('Successfully connected as id: ' + connection.getId())
      }
    })

    const snowFlakeData = async (orderId: string): Promise<void> => {
     

      try {
        const sql = `
          SELECT
          online_store_transaction_id AS order_number,
          updated_at_ts,
          progress,
          status,
          service_time,
          site_name
          FROM
          DATABASE.delivery
          WHERE
          online_store_transaction_id = '${orderId}'
      `

        const anotherSql = `
          SELECT
          online_store_transaction_id as order_number,
          customer_called_at_ts
          FROM
          DATABASE.customer
          WHERE
          online_store_transaction_id = '${orderId}'
      `
        let data: unknown = {} // Global variable 

        connection.execute({
          sqlText: sql,
          fetchAsString: ['Number'],

          complete: function (err, stmt, rows) {
            if (err) {
              console.error('Failed to execute statement due to the following error: ' + err.message)
            } else {
              if (!rows) {
                throw new Error('Data not found')
              }
              console.log('Successfully executed statement: ' + stmt.getSqlText())

              rows.forEach((test: void) => (data = test)) // passing the value
            }
          },
        })

        console.log({ data })//  return empty object first
        

        let callData: unknown = {} // Global variable 

        connection.execute({
          sqlText: anotherSql,
          fetchAsString: ['Number'],
          complete: function (err, stmt, rows) {
            if (err) {
              console.error('Failed to execute statement due to the following error: ' + err.message)
            } else {
              if (!rows) {
                throw new Error('Data not found')
              }
              console.log('Successfully executed statement: ' + stmt.getSqlText())

              rows.forEach((test: void) => (callData = test)) // passing the value
            }
          },
        })

        console.log({ callData }) //  return empty object first

      } catch (error) {
        console.log(error)
      }
    }

**Comment by sfc-gh-dszmolka** [comment]
hi, this submission does not seem to be an actual issue with the Snowflake nodejs connector. For usage advice and hints, please head to the [Stackoverflow community](https://community.snowflake.com/s/article/Snowflake-Community-on-Stack-Overflow-Know-Before-You-Go). closing this issue.
