### ISSUE TITLE
Documentation: fetchAsString accepts 'Buffer' as a valid value

### ISSUE THREAD

**Issue by nathanjcochran** [snowflakedb/snowflake-connector-nodejs#351]
This [error message](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/0c7eea1c3056c54f1a1a7b18b57a683393b8cb5b/lib/constants/error_messages.js#L45) suggests that the valid arguments to `fetchAsString` are: `String`, `Boolean`, `Number`, `Date`, and `JSON`. However, it also accepts `Buffer`, which correctly prevents `BINARY` data types from being returned as Buffers (which is the default behavior - see [here](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/0c7eea1c3056c54f1a1a7b18b57a683393b8cb5b/lib/connection/result/data_types.js#L246)).

The snowflake-sdk [validates](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/5848cb627cf9ad5b90e0e2a69b4a1abd4b7cefc3/lib/connection/connection_config.js#L331-L334) that the arguments to `fetchAsString` are in this [list of native types](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/5848cb627cf9ad5b90e0e2a69b4a1abd4b7cefc3/lib/connection/result/data_types.js#L192-L197), which includes `Buffer`. And the [logic](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/0c7eea1c3056c54f1a1a7b18b57a683393b8cb5b/lib/connection/result/row_stream.js#L365-L381) that actually handles the `fetchAsString` config option works correctly when `'Buffer'` is provided as an argument. I therefore believe that the error message should be updated to reflect the fact that `'Buffer'` is a valid `fetchAsString` value. Furthermore, [these docs](https://docs.snowflake.com/en/user-guide/nodejs-driver-use.html#fetching-data-types-as-strings), which seem to suggest that `fetchAsString` only accepts `Number` and `Date`, should be updated to reflect all valid values.

**Comment by sfc-gh-dszmolka** [comment]
hi, thank you for submitting this issue, and especially for the descriptive report, much appreciated ! this has now been passed to the relevant teams (driver + Docs) and we'll take a look.

**Comment by sfc-gh-dszmolka** [comment]
#526

**Comment by sfc-gh-dszmolka** [comment]
thank you for the patience here. The PR has been merged so the error message should be amended now and the change is available with the next release. I also reached out to the Docs team to amend the official documentation accordingly; I don't have a timeline for that.

**Comment by sfc-gh-dszmolka** [comment]
fix is out with release 1.6.23
