### ISSUE TITLE
Keep alive ping using a select statement. Incurs cost on data warehouse.

### ISSUE THREAD

**Issue by kri5t** [snowflakedb/snowflake-connector-nodejs#354]
Please answer these questions before submitting your issue. Thanks!

1. What version of NodeJS are you using (`node --version` and `npm --version`)?
16.13

2. What operating system and processor architecture are you using?
macOS 12.2

3. What are the component versions in the environment (`npm list`)?
snowflake-sdk: 1.6.11

4. What did you do?
`new SnowflakeSDKConnection({ ...options, clientSessionKeepAlive: true });`

5. What did you expect to see?
Just a connection that was kept alive. Not a `select 1` every hour per connection we didn't properly close.

6. What did you see instead?
I saw a bunch of weird select statements in our snowflake

I don't understand why querying the database is needed to keep this alive? It seems like an ugly hack that shows up on usage in Snowflake.

![image](https://user-images.githubusercontent.com/1608179/198588497-94e48ffa-92e6-4c3d-9873-1a0ac3eea083.png)

7. Add this to get standard output.
 Look at the screenshot.

**Comment by sfc-gh-dszmolka** [comment]
hi @kri5t , thank you for raising this concern. we'll take a look how to best address this current behaviour.
