### ISSUE TITLE
(node:8) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

### ISSUE THREAD

**Issue by joehoppe** [snowflakedb/snowflake-connector-nodejs#357]
Please answer these questions before submitting your issue. Thanks!

1. What version of NodeJS are you using (`node --version` and `npm --version`)?
node -v
v16.16.0

npm --version
8.11.0

3. What operating system and processor architecture are you using?
AWS lambda
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

Linux:
    > cat /etc/redhat-release for RedHat OS variants,
    > lsb_release -a for Debian OS variants
Mac:
    > system_profiler SPSoftwareDataType
Windows:
    > systeminfo | findstr /B /C:"OS Name" /C:"OS Version"

5. What are the component versions in the environment (`npm list`)?
"snowflake-promise": "^4.5.0",
    "node_modules/snowflake-sdk": {
      "version": "1.6.15",

7. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

8. What did you expect to see?
No error logged

9. What did you see instead?
ERROR	(node:8) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (node:buffer:187:11)
    at new Buffer (node:buffer:271:3)
    at node_modules/formstream/lib/formstream.js (/var/task/index.js:94682:27)
    at __require (/var/task/index.js:9:50)
    at node_modules/urllib/lib/urllib.js (/var/task/index.js:132129:22)
    at __require (/var/task/index.js:9:50)
    at node_modules/urllib/lib/index.js (/var/task/index.js:133301:18)
    at __require (/var/task/index.js:9:50)
    at NodeHttpClient.sendRequest2 (/var/task/index.js:133374:19)
    at Gzip.cb (/var/task/index.js:133397:11)

11. Add this to get standard output.
 
```
var snowflake = require('./snowflake');
snowflake.configure(
{
  logLevel: 'trace'
});
```

My AWS lambda is using snowflake-sdk. I'm getting the error logged above. It is a deprecation warning - I haven't noticed any other side effects.

It looks like snowflake-sdk has a dependency on urllib, and urllib is using a deprecated Buffer() call.

Is it slated to either upgrade urllib or remove urllib to get rid of this warning?

Thanks

**Comment by blazejkustra** [comment]
More info here #363

**Comment by sfc-gh-dszmolka** [comment]
thank you for submitting this issue. we'll take a look.

**Comment by sfc-gh-dszmolka** [comment]
closing this for now , should be fixed by `formstream 1.2.0` which is automatically installed with every new installation of the `snowflake-sdk`.
if you still see this issue, please update this issue and i'll reopen it for you.

**Comment by miladr0** [comment]
hi @sfc-gh-dszmolka,
I installed version `1.6.22` but still see this issue!
I'm using AWS lambda with Node v14

**Comment by sfc-gh-dszmolka** [comment]
hi @miladr0 please make sure `formstream 1.2.0` is installed on your runtime, the third party fixed the deprecation in that version.
on the long run, we'll also replace `urllib` 2 with something else (either upgrade to `urllib` 3 or replace entirely with something else) but for now, that's the fix.
