### ISSUE TITLE
Runtime.ImportModuleError: Error: Cannot find module 'async'

### ISSUE THREAD

**Issue by deepak-panwar-paf** [snowflakedb/snowflake-connector-nodejs#394]
Please answer these questions before submitting your issue. Thanks!

1. What version of NodeJS are you using (`node --version` and `npm --version`)?
v18.12.1
2. What operating system and processor architecture are you using?
Mac:
    System Software Overview:
      System Version: macOS 12.6 (21G115)
      Kernel Version: Darwin 21.6.0

3. What are the component versions in the environment (`npm list`)?
snowflake-sdk@1.6.17
4. What did you do?
getting import error that Cannot find module 'async'"
as per snowflake-sdk's package.json  'async' is a dev dependency and should not throw this error if 'async' is not available in node_modules

see 
https://github.com/snowflakedb/snowflake-connector-nodejs/blob/master/lib/connection/statement.js#L5
change was introduced by 
https://github.com/snowflakedb/snowflake-connector-nodejs/pull/328

ERROR:

{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'async'\nRequire stack:\n- /var/task/node_modules/snowflake-sdk/lib/connection/statement.js\n- /var/task/node_modules/snowflake-sdk/lib/connection/connection.js\n- /var/task/node_modules/snowflake-sdk/lib/core.js\n- /var/task/node_modules/snowflake-sdk/lib/snowflake.js\n- /var/task/node_modules/snowflake-sdk/index.js\n- 
"trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'async'",
    "Require stack:",
    "- /var/task/node_modules/snowflake-sdk/lib/connection/statement.js",
    "- /var/task/node_modules/snowflake-sdk/lib/connection/connection.js",
    "- /var/task/node_modules/snowflake-sdk/lib/core.js",
    "- /var/task/node_modules/snowflake-sdk/lib/snowflake.js",
    "- /var/task/node_modules/snowflake-sdk/index.js",

6. What did you expect to see?
no import error for 'async' since it is dev dependency as per
snowflake-sdk's package.json

7. What did you see instead?
import error for 'async' since it is dev dependency

**Comment by samason** [comment]
I'm running into the same issue when attempting to use the SDK via a Lambda function.

**Comment by sfc-gh-dszmolka** [comment]
we're going to take a look, thank you for reporting.

**Comment by samason** [comment]
Thanks @sfc-gh-dszmolka, appreciate it. I am happy to provide any additional details or answer any questions if you have trouble reproducing the issue.

**Comment by thedude459** [comment]
Any update or work around for this?

**Comment by sfc-gh-dszmolka** [comment]
i'll post any updates if there's any, for now, there isn't. than you for bearing with us.

**Comment by deepak-panwar-paf** [comment]
> 6\. async



> Any update or work around for this?
@thedude459 
work around for this is to install `async` as dependency in your project

**Comment by thedude459** [comment]
I added async into my layer and I am still getting the same error.

**Comment by samason** [comment]
Installing `async` as a dependency in my project resolved this issue but now I'm getting the same error as #293. It seems like there might be a larger overarching error related to dependencies inside the package.

**Comment by sfc-gh-dszmolka** [comment]
https://github.com/snowflakedb/snowflake-connector-nodejs/pull/462

**Comment by sfc-gh-dszmolka** [comment]
fix released with [1.6.21](https://github.com/snowflakedb/snowflake-connector-nodejs/releases/tag/v1.6.21)
