### ISSUE TITLE
upgrade jsonwebtoken to 9.0.0 to remedy vulnerability

### ISSUE THREAD

**Issue by livgust** [snowflakedb/snowflake-connector-nodejs#399]
Hi, there is a [documented vulnerability](https://github.com/advisories/GHSA-27h2-hvpr-p74q) in the `jsonwebtoken` package. Packages 8.5.1 and under are vulnerable, and there's a published fix in 9.0.0. Could you please upgrade? I saw that your most recent version, 1.6.17, is still on jsonwebtoken@8.5.1.

**Comment by livgust** [comment]
@sfc-gh-dszmolka apologies to tag you - but the Jira creation run failed so wanted to make sure this got seen.

**Comment by sfc-gh-dszmolka** [comment]
@livgust no worries at all. i see there's already a PR which ought to address this (#390) . i'll try to get this prioritized.

**Comment by livgust** [comment]
Fabulous, thank you!

**Comment by sfc-gh-dszmolka** [comment]
apologies, i linked the wrong pr. the correct one is #393 and it's already merged. the code already has jsonwebtoken 9.0.0 so the next release of snowflake-sdk will have the upgraded dependency.
if you agree, this issue can be closed.

**Comment by livgust** [comment]
Will do! Thanks.
