### ISSUE TITLE
Need clear example of binding an (arbitrarily large) array as source data for a MERGE statement.

### ISSUE THREAD

**Issue by ksze** [snowflakedb/snowflake-connector-nodejs#404]
Please answer these questions before submitting your issue. Thanks!

1. What version of NodeJS are you using (`node --version` and `npm --version`)?
node v18.13.0
npm 9.3.1

2. What operating system and processor architecture are you using?
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
```

3. What are the component versions in the environment (`npm list`)?
```
├── @azure/storage-blob@12.12.0
├── @babel/preset-env@7.20.2
├── @babel/preset-typescript@7.18.6
├── @shopify/eslint-plugin@42.0.3
├── @types/async-retry@1.4.5
├── @types/chai@4.3.4
├── @types/compression@1.7.2
├── @types/cors@2.8.13
├── @types/express@4.17.15
├── @types/lodash@4.14.191
├── @types/luxon@3.2.0
├── @types/mocha@10.0.1
├── @types/morgan@1.9.4
├── @types/node@18.11.18
├── @types/snowflake-sdk@1.6.12
├── @types/swagger-ui-express@4.1.3
├── @types/yamljs@0.2.31
├── @typescript-eslint/eslint-plugin@5.48.2
├── @typescript-eslint/parser@5.48.2
├── async-retry@1.3.3
├── chai-http@4.3.0
├── chai-pretty-expect@1.0.1
├── chai@4.3.7
├── compression@1.7.4
├── cors@2.8.5
├── dotenv-safe@8.2.0
├── dotenv@16.0.3
├── eslint-plugin-deprecation@1.3.3
├── eslint@8.32.0
├── express@4.18.2
├── fp-ts@2.13.1
├── husky@8.0.3
├── io-ts@2.2.20
├── lint-staged@13.1.0
├── lodash@4.17.21
├── luxon@3.2.1
├── mocha@10.2.0
├── morgan@1.10.0
├── mysql2@3.0.1
├── nodemon@2.0.20
├── sequelize@6.28.0
├── snowflake-sdk@1.6.17
├── swagger-cli@4.0.4
├── swagger-ui-express@4.6.0
├── ts-node@10.9.1
├── typescript@4.9.4
├── winston@3.8.2
└── yamljs@0.3.0
```
4. What did you do?
Try to bind a large array of rows for a MERGE statement.

5. What did you expect to see?
Clear documentation about how to do this.

6. What did you see instead?
The documentation only talks about binding an array for an INSERT statement. But the syntax of MERGE the statement is so different that it is not clear how I could bind an array for it.

I have a very hacky workaround where I `JSON.stringify()` the array in Node.js and bind it as a (possibly very very long) string. And then in the SQL, I have:
```
MERGE INTO my_schema.my_table AS target
USING (
  SELECT
    value
  FROM TABLE(FLATTEN(PARSE_JSON(:1)))
) as source ON
...
```

The problem I now face is that the statement can fail if the JSON is even slightly large.

**Comment by ksze** [comment]
A colleague suggested that I create a temporary table, insert the data to the temporary table using the usual array binding, and then merge to the target table using the temporary table as source. This way, I don't have to bind a potentially very very long JSON string to the MERGE query.

While this solution "works" in the most naïve sense of the word, it is not good enough for me because creating a temporary table is considered DDL, and it needs to be run outside the usual transaction, otherwise I cannot rollback either upon error or on purpose.

That means the sequence of actions of my use case need to be like this:
```
u1. create temporary table
u2. check whether a transaction has already been started
    u2.1. if no transaction yet, start transaction
    u2.2. otherwise, internal transaction_nesting_level_counter+=1
u3. execute the usual queries for the business logic
u4. check whether we are in a fake nested transaction
    u4.1 if so, internal transaction_nesting_level_counter-=1
    u4.2 otherwise, commit
```

The problem is that I have a test fixture that wraps my entire test case in a transaction, such that I can test the use case and then easily revert any change. When the use case is run in a test case, the steps u2.2 and u4.2 are run instead of u2.1 and u4.1, respectively, since Snowflake does not support nested transactions other than in stored procedures:
```
t1. start transaction (for real)
u1. create temporary table
u2. check whether a transaction has already been started
    u2.1. if no transaction yet, start transaction
    u2.2. otherwise, internal transaction_nesting_level_counter+=1
u3. execute the usual queries for the business logic
u4. check whether we are in a top level transaction
    u4.1 if so, commit
    u4.2 otherwise, internal transaction_nesting_level_counter-=1
t2. rollback transaction (for real)
```

There is no clean way for me to extract step u1 to the outside of the real transaction _just for running tests_. I could write my use case like this:
```
u1. check whether we are inside a test run
    u1.1. if not inside a test run, create temporary table
u2. check whether a transaction has already been started
    u2.1. if no transaction yet, start transaction
    u2.2. otherwise, internal transaction_nesting_level_counter+=1
u3. execute the usual queries for the business logic
u4. check whether we are in a top level transaction
    u4.1 if so, commit
    u4.2 otherwise, internal transaction_nesting_level_counter-=1
```

And then I wrap my use case in my test case:
```
t1 create temporary table
t2. start transaction (for real)
u1. check whether we are inside a test run
    u1.1. if not inside a test run, create temporary table
u2. check whether a transaction has already been started
    u2.1. if no transaction yet, start transaction
    u2.2. otherwise, internal transaction_nesting_level_counter+=1
u3. execute the usual queries for the business logic
u4. check whether we are in a top level transaction
    u4.1 if so, commit
    u4.2 otherwise, internal transaction_nesting_level_counter-=1
t3. rollback transaction (for real)
```

But this feel quite dirty.

**Comment by sfc-gh-dszmolka** [comment]
hi, thank you for raising this issue. going forward, we need the community to submit their requests to their appropriate places:
* production affecting issues originating from snowflake-sdk: kindly [raise a case with Snowflake Support](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge)
* issues and feature requests: please do raise an Issue in this repo. (Note: for feature requests, there's no timeline guarantee on the response or the implementation)
* usage advice, 'how to do..': kindly post to [Snowflake Stackoverflow](https://community.snowflake.com/s/article/Snowflake-Community-on-Stack-Overflow-Know-Before-You-Go)

with that said, I'm now marking this Issue as closed. please feel free to reopen it if you think this is caused due to a bug. in that case, we'll kindly request you to post a reproduction code snippet, which when run, can reproduce the issue you're having. thank you in advance !
