### ISSUE TITLE
Please help! Issue setting up SequelizeModule with proxy for Snowflake DB

### ISSUE THREAD

**Issue by TASimpson** [snowflakedb/snowflake-connector-nodejs#408]
Please answer these questions before submitting your issue. Thanks!

1. 16.15.1

2. Windows & Mac

3. ??

4. What did you do?
Everything has been working great! However, I have been tasked to have the Snowflake DB connection go through a proxy. I have not been able to find a solution and I have tried a few with no success. Please help me determine how I need to set this up so that our application can go to Production without a total rewrite! The below is my set up in my app.module.ts. What do I need to add to make this work??

```
    SequelizeModule.forRoot({
      dialect: 'snowflake',
      host: 'localhost',
      dialectOptions: {
        account: 'snowflake_account_here',
        application: 'SNOWFLAKE',
        role: 'snowflake_role_here',
        warehouse: 'snowflake_warehouse_here',
        schema: 'snowflake_schema_here'
      },
      username: 'snowflake_username_here',
      password: 'snowflake_password_here',
      database: 'snowflake_database_here',
      define : {
        freezeTableName: true
      },
      models: ([...list of models here]),
      quoteIdentifiers: false
    })
```

I have tried the following with NO success:

Added the following under dialectOptions

```
host: 'url to proxy'
port: 'port to proxy'
```

AND

```
stream : {
   host: 'url to proxy'
   port: 'port to proxy'
}
```

AND

```
proxyHost: 'url to proxy'
proxyPort: 'port to proxy'
```

5. What did you expect to see?
  I just want a path to figure out how to add the proxy to the sequelize module please!

6. What did you see instead?
  I cannot find a path 

8. Add this to get standard output.
 No errors, I just cannot get it to successfully proxy the connection!

**Comment by sfc-gh-dszmolka** [comment]
hi, thank you for raising this issue ! it doesn't seem like something which is actually an _issue_ with the node.js connector, rather an usage question. for the sake of keeping this repo well kempt going forward, i suggest raising 'how to' questions on [Stackoverflow](https://community.snowflake.com/s/article/Snowflake-Community-on-Stack-Overflow-Know-Before-You-Go) instead.  thank you for understanding !

however, if you did discover an actual issue or unexpected behaviour with the connector, please feel free to reopen this item.

**Comment by TASimpson** [comment]
ok, i did do a stackoverflow. I was just hoping someone could help...
