### ISSUE TITLE
Typings Files

### ISSUE THREAD

**Issue by kostenickj** [snowflakedb/snowflake-connector-nodejs#41]
Would be extremely helpful, especially when using typescript

**Comment by casey-largent** [comment]
Can we get some movement on this? My company is looking to use Typescript with the Snowflake Node Connector, but there is none and I don't want to make any assumptions.

**Comment by smtakeda** [comment]
We don't have a plan in the short term.

**Comment by sshivananda** [comment]
@smtakeda Are folks are interested in using typescript in the package - I can submit PRs to update the code (would be a series of PRs - one per file : to make reviews and merging simpler). This would generate typings automatically and also add type safety to the code.
As part of the verification - we can test whether the current js file and the generated js file match.

**Comment by atsu85** [comment]
Are there still issues with TypeScript types? I found [@types/snowflake-sdk](https://www.npmjs.com/package/@types/snowflake-sdk) package, but i'm wondering about its quality (just started looking into Snowflake, so i havent tried it myself)

**Comment by sfc-gh-dszmolka** [comment]
seeing that we did not have short term plans for this in 2019 and after 3.5 years, there are still no plans for it to my best knowledge , furthermore @types/snowflake-sdk seems to implement the requirement

considering all of the above, I'm now closing this issue . will reopen/update should the above change.

**Comment by brianzinn** [comment]
@sfc-gh-dszmolka  Do you maintain `@types/snowflake-sdk`?  I am trying to add `arrayBindingThreshold`  connection option and forced to `any` cast.

**Comment by sfc-gh-dszmolka** [comment]
hi @brianzinn no we do not maintain it (for now at least). their [CODEOWNERS](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.github/CODEOWNERS#L7605) file suggests maybe you could try to contact these folks:
```
/types/snowflake-sdk/                                     @htunnicliff @orellabac @boatilus @briangottfried
```
