### ISSUE TITLE
Support passing host as connection option

### ISSUE THREAD

**Issue by MasterOdin** [snowflakedb/snowflake-connector-nodejs#413]
I would like to be able to pass the host as a connection option and omit `account`. My ultimate goal is to use the `snowflake-sdk` library in conjunction with the [dbt Semantic Layer](https://docs.getdbt.com/guides/dbt-ecosystem/sl-partner-integration-guide#query-the-dbt-semantic-layer) which acts as a reverse proxy to snowflake, performing a compilation step before sending it to snowflake to be executed.

----- 

Please answer these questions before submitting your issue. Thanks!

1. What version of NodeJS are you using (`node --version` and `npm --version`)? `16.19.0`

2. What operating system and processor architecture are you using?

```
Software:

    System Software Overview:

      System Version: macOS 13.1 (22C65)
      Kernel Version: Darwin 22.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: popsql2
      User Name: Matthew Peveler (mpeveler)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 6 days, 13 hours, 12 minutes
```

3. What are the component versions in the environment (`npm list`)? `snowflake-sdk@1.6.10`

4. What did you do?

```
const snowflake = require('snowflake-sdk');
client = snowflake.createConnection({
  host: 'account.snowflakecomputing.com',
  database: 'SNOWFLAKE_SAMPLE_DATA',
  warehouse: 'WAREHOUSE',
  username: 'user',
  password: 'pass',
});
```

5. What did you expect to see?

A successful connection using the inputed host.

7. What did you see instead?

```
Uncaught Error [MissingParameterError]: An account must be specified.
    at createError (/Users/mpeveler/code/node_modules/snowflake-sdk/lib/errors.js:536:15)
    at Object.exports.checkArgumentExists (/Users/mpeveler/code/node_modules/snowflake-sdk/lib/errors.js:219:11)
    at consolidateHostAndAccount (/Users/mpeveler/code/node_modules/snowflake-sdk/lib/connection/connection_config.js:113:10)
    at new ConnectionConfig (/Users/mpeveler/code/node_modules/snowflake-sdk/lib/connection/connection_config.js:167:5)
    at createConnection (/Users/mpeveler/code/node_modules/snowflake-sdk/lib/core.js:73:7)
    at Object.createConnection (/Users/mpeveler/code/node_modules/snowflake-sdk/lib/core.js:97:16) {
  code: 404007,
  sqlState: undefined,
  data: undefined,
  response: undefined,
  responseBody: undefined,
  cause: undefined,
  isFatal: undefined
}
```

**Comment by sfc-gh-dszmolka** [comment]
hi there, thank you for submitting this issue. i'm now internally checking with the product team if there are any plans in supporting the dbt semantic layer in the node.js driver in the foreseeable future. will post the updates here once i have any and thank you for bearing with us!

**Comment by MasterOdin** [comment]
I'm not really asking for the node.js driver to have any sort of support for dbt semantic layer, I was just using that as an example of something that currently cannot work with the driver because the driver doesn't allow specifying just a host, and that if I put in account, then the value of host I input looks to be overwritten.

An example of something that does currently fit my needs is dbeaver, where it just simply asks for host on its connection form:
<img width="689" alt="Screenshot 2023-02-02 at 10 57 21 AM" src="https://user-images.githubusercontent.com/1845314/216375099-6001e971-7858-4dc8-a631-1a7860dfd830.png">

It nudges you to use `.snowflakecomputing.com` as part of the hostname, but allows me to put whatever, which is really what I'm asking for here.

**Comment by sfc-gh-dszmolka** [comment]
oops, apologies, i might have then misunderstood what the goal is here
> My ultimate goal is to use the snowflake-sdk library in conjunction with the [dbt Semantic Layer](https://docs.getdbt.com/guides/dbt-ecosystem/sl-partner-integration-guide#query-the-dbt-semantic-layer) which acts as a reverse proxy to snowflake,

the difference is (or at least one for sure) that with DBeaver you have an additional layer over your driver (say, JDBC driver). With JDBC, you end up having the connection string (in DBeaver, it seems to be by default this format: `jdbc:snowflake://{host}[:port]/?[db={database}]` (Connection > Driver settings > URL template), so in the end the driver knows to which Snowflake account it needs to connect. 

reading [dbt Semantic Layer docs here](https://docs.getdbt.com/docs/use-dbt-semantic-layer/dbt-semantic-layer) , this feature seems to be not even GA yet, instead open for a public preview, and only seems to work with dbt cloud - which suggest to me you cannot just go into any Snowflake driver today and manually configure the dbt semantic layer endpoint.

If I get this correctly, you would [need to configure it in dbt Cloud](https://docs.getdbt.com/docs/use-dbt-semantic-layer/quickstart-semantic-layer#set-up-dbt-semantic-layer) instead, and not Snowflake, thus not in the Snowflake driver. Or I'm missing something.

You also mentioned
> an example of something that currently cannot work with the driver because the driver doesn't allow specifying just a host

that is indeed true. can you clarify this issue please, why is it not possible/desirable to populate the `account` field in the connection configuration? Per the documentation, it is currently a [required connection option](https://docs.snowflake.com/en/user-guide/nodejs-driver-use.html#required-connection-options) and it seems to behave accordingly. I would like to understand the particular situation, where it is possible to populate the `host` option and not possible to populate the `account`, if it's not the dbt semantic layer - and why it would be required to change this behaviour, if not to support the above product. 

I'd also like to point out that (in general) reverse proxies are not supported with any of the Snowflake drivers.

**Comment by MasterOdin** [comment]
> If I get this correctly, you would [need to configure it in dbt Cloud](https://docs.getdbt.com/docs/use-dbt-semantic-layer/quickstart-semantic-layer#set-up-dbt-semantic-layer) instead, and not Snowflake, thus not in the Snowflake driver. Or I'm missing something.

You setup the semantic layer in dbt Cloud, and you get back a URL to use for the host field for your snowflake connection. However, there's no documented host field for the driver, only `account`, which I don't need in the driver as that info is already captured within the reverse proxy.

> can you clarify this issue please, why is it not possible/desirable to populate the account field in the connection configuration? Per the documentation, it is currently a [required connection option](https://docs.snowflake.com/en/user-guide/nodejs-driver-use.html#required-connection-options) and it seems to behave accordingly.

It's required _now_, but that's only (to my eyes) so it can be concatenated with `snowflakecomputing.com` to get the host url to communicate with. If I'm allowed to pass in my own URL, then wouldn't the `account` field be pointless / ignored really?

> if it's not the dbt semantic layer - and why it would be required to change this behaviour, if not to support the above product.

dbt semantic layer is just an example of why I personally am filing this ticket, but maybe someone out in the wild will hit some other system that wants you to be able to put in a custom URL.

---

Digging into the source, turns out it is currently possible to do this with an undocumented config option: `accessUrl`:

```
const snowflake = require('snowflake-sdk');

const connection = snowflake.createConnection({
  accessUrl: 'https://abcdefg.proxy.cloud.getdbt.com',
  username: 'user',
  password: 'pass',
  database: 'database',
  warehouse: 'warehouse',
  account: 'account',
  role: 'PUBLIC',
});

connection.connect((err) => {
  if (err) {
    console.error('Unable to connect: ' + err.message);
    process.exit(0);
  }
  connection.execute({
    sqlText: "SELECT '{{ dbt_version }}'",
    complete: function(err, stmt, rows) {
      if (err) {
        console.error('Failed to execute statement due to the following error: ' + err.message);
      } else {
        console.log('Successfully executed statement: ' + stmt.getSqlText());
        console.log(rows);
      }
      process.exit(0);
    }
  });
});
```

where when I comment out `accessUrl`, I get a response as run straight against the database and when I use `accessUrl`, I get the response passed through the proxy. I still need to set the `account` field, but for all intents and purposes it seems to be ignored.

This solves my problem, albeit using an undocumented feature that could go away, so I guess my ask would be to document it so I have confidence that it'll remain and keep working as expected.

Of course, you state:

> I'd also like to point out that (in general) reverse proxies are not supported with any of the Snowflake drivers.

so :shrug:

**Comment by sfc-gh-dszmolka** [comment]
thank you for the explanation here, how the dbt semantic layer should work. can't say i'm personally familiar with it so definitely useful for me 👍 

also indeed `accessUrl` can be used as an undocumented way to connect to a given endpoint and I'm really not sure at this point if we really intended to have it undocumented. so reached out to the Documentation team to document it, and also the driver team to consider making `account` optional, if `accessUrl` is set (if its value is widely ignored anyways, why require it in the config)

but for now, good to see you're unblocked, so marking this issue as closed. please feel free to reopen it if you still need further assistance with it.
