### ISSUE TITLE
SNOW-751545: Update nodejs version to 14.0.0 on docker image centos7-fips-test

### ISSUE THREAD

**Issue by sfc-gh-ext-simba-dl** [snowflakedb/snowflake-connector-nodejs#429]
Please build the docker image for centos7-fips-test with nodejs version to 14.0.0 and push the image to github.

**Comment by sfc-gh-dszmolka** [comment]
@sfc-gh-ext-simba-dl if this is not resolved yet, could you please kindly open an internal one ? TYVM!
