### ISSUE TITLE
SNOW-774060: Improve test documentation  and DX for testing

### ISSUE THREAD

**Issue by hirohito-protagonist** [snowflakedb/snowflake-connector-nodejs#463]
## What is the current behavior?

As a developer I need to install `nyc` by myself to generate code coverage and I am force to extend 
`scripts` in package.json to run the unit test in watch mode. 

## What is the desired behavior?

It is to have everything installed that it is needed to develop the connector.

So I expect to have installed code coverage tool so the entry in package.json needs to be added like this

```json
  "devDependencies": {
    "async": "^3.2.3",
    "mocha": "^10.1.0",
    "nyc": "^15.1.0",
    "qs": "^6.10.3"
  },
```

Also is possible to add custom run `commands` in `package.json`. So for the test coverage and unit test watch  you could add below entries

```json
  "scripts": {
    "test": "mocha test/unit/**/*.js",
    "test:watch": "mocha --watch test/unit/**/*.js",
    "test:coverage": "nyc mocha test/**/*.js"
  },
```

Then from the shell we could simply run

Command for TDD approach:

```shell
npm run test:watch
```

Command to generate code coverage:
```shell
npm run test:coverage
```

After that the `README.md` file needs to be updated.

## How would this improve `snowflake-connector-nodejs`?

It will improve developer experience for those who want to contribute to the repo.
The devs are force to install `nyc` manually to see the code coverage and manipulate the scripts entry as well 
if they want to fallow the TDD appraoch.

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for submitting this enhancement request with us, the team will take a look. can't estimate any timeline though, so thank you for bearing with us

**Comment by sfc-gh-dszmolka** [comment]
`nyc` PR is merged, so closing this one
