### ISSUE TITLE
SNOW-777130: connect succeeds, connectAsync throws exception

### ISSUE THREAD

**Issue by edtguy** [snowflakedb/snowflake-connector-nodejs#464]
Please answer these questions before submitting your issue. Thanks!

1. What version of NodeJS are you using (`node --version` and `npm --version`)?
$ node --version
v12.18.3
$ npm --version
6.14.8

2. What operating system and processor architecture are you using?

Windows:
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19045 N/A Build 19045

3. What are the component versions in the environment (`npm list`)?
$ npm list --depth 0
myApp@1.0.0 C:\Users\Ed\projects\myApp
+-- @panva/jose@0.11.5
+-- aws-iot-device-sdk@2.2.10
+-- aws-sdk@2.257.1
+-- bluebird@3.5.1
+-- csvtojson@2.0.10
+-- fs-extra@7.0.1
+-- jws@3.1.5
+-- moment-timezone@0.5.27
+-- mysql@2.17.1
+-- mysql2@1.5.3
+-- node-schedule@1.3.1
+-- nodemailer@5.1.1
+-- redis@2.8.0
+-- request@2.87.0
+-- request-promise@4.2.2
+-- restify@6.4.0
+-- restify-cors-middleware@1.1.1
+-- restify-errors@6.1.0
+-- restify-session@1.1.1
+-- sequelize@4.44.3
+-- shortid@2.2.14
+-- snowflake-sdk@1.6.17
+-- tar-stream@1.6.1
`-- unirest@0.6.0

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
/* Original successfull code, although console output  'I want the last word!' is output first. */
```javascript
const snowflake = require('snowflake-sdk')
snowflake.configure(
{
  logLevel: 'trace'
})
var myConfig = {
    account: '{myAccount}',
    username: '{myUsername}',
    password: '{myPassword}',
    application: '{myApplication}',
    database: 'ADDEMO',
    role: 'SYSADMIN',
    schema: 'PUBLIC',
    warehouse: 'COMPUTE_WH'
}
var connection = snowflake.createConnection(myConfig)

kickoff()

function kickoff(argument) {
    let foobar = connection.connect(getList)
    // how do I wait for getList to complete before executing the next statement?
    console.log('I want the last word!')
}

function getList(err,conn) {
    if(err) {
        console.error()
    }
    else {
        var statement = conn.execute(
            {sqlText: '{select statement that returns multiple rows}'}
        )
        var stream = statement.streamRows()
        stream.on('error', err => {
            console.error('Failure:',err.message)
        })
        stream.on('data', row => {
            console.log('row message')
        })
        stream.on('end', () => {
            connection.destroy((err,conn) => {
                if (err) {
                    console.log('Unable to disconnect from Snowflake:',err.message)
                }
                else {
                    console.log('Sucessfully disconnected.')
                }
            })
        })
    }
}
``` 
/* modified code to wait for connectAsync */
```javascript
const snowflake = require('snowflake-sdk')
snowflake.configure(
{
  logLevel: 'trace'
})
var myConfig = {
    account: '{myAccount}',
    username: '{myUsername}',
    password: '{myPassword}',
    application: '{myApplication}',
    database: 'ADDEMO',
    role: 'SYSADMIN',
    schema: 'PUBLIC',
    warehouse: 'COMPUTE_WH'
}
var connection = snowflake.createConnection(myConfig)

kickoff()

async function kickoff(argument) {
    let foobar = await connection.connectAsync(getList)
    // how do I wait for getList to complete before executing the next statement?
    console.log('I want the last word!')
}

async function getList(err,conn) {
    if(err) {
        console.error()
    }
    else {
        var statement = conn.execute(
            {sqlText: '{select statement that returns multiple rows}'}
        )
        var stream = statement.streamRows()
        stream.on('error', err => {
            console.error('Failure:',err.message)
        })
        stream.on('data', row => {
            console.log('row message')
        })
        stream.on('end', () => {
            connection.destroy((err,conn) => {
                if (err) {
                    console.log('Unable to disconnect from Snowflake:',err.message)
                }
                else {
                    console.log('Sucessfully disconnected.')
                }
            })
        })
    }
}

``` 
5. What did you expect to see?
C:\Users\Ed\projects>node myApp.js
{"level":"DEBUG","message":"[2:42:25.4225 PM]: Contacting SF: /session/v1/login-request?requestId=feeb3989-8d23-4814-8b22-61f91233f9ef&warehouse=COMPUTE_WH&databaseName=ADDEMO&schemaName=PUBLIC&roleName=SYSADMIN, (1/5)"}
{"level":"TRACE","message":"[2:42:25.4225 PM]: https://AQA19782.us-east-1.snowflakecomputing.com/session/v1/login-request?requestId=feeb3989-8d23-4814-8b22-61f91233f9ef&warehouse=COMPUTE_WH&databaseName=ADDEMO&schemaName=PUBLIC&roleName=SYSADMIN"}
{"level":"DEBUG","message":"[2:42:25.4225 PM]: Reading OCSP cache file. C:\\Users\\Ed.Winterfell\\AppData\\Local\\Snowflake\\Caches\\ocsp_response_cache.json"}
{"level":"TRACE","message":"[2:42:26.4226 PM]: Returning OCSP status for certificate 01A1D25F4A87679A7BF8F6387C3E4263 from cache"}
{"level":"TRACE","message":"[2:42:26.4226 PM]: Returning OCSP status for certificate 0773124A4BCBD44EC7B53BEAF194842D3A0FA1 from cache"}
{"level":"TRACE","message":"[2:42:26.4226 PM]: Returning OCSP status for certificate 067F944A2A27CDF3FAC2AE2B01F908EEB9C4C6 from cache"}
{"level":"TRACE","message":"[2:42:26.4226 PM]: Returning OCSP status for certificate A70E4A4C3482B77F from cache"}
{"level":"TRACE","message":"[2:42:26.4226 PM]: socket reused = false"}
{"level":"TRACE","message":"[2:42:26.4226 PM]: OCSP validation succeeded for aqa19782.us-east-1.snowflakecomputing.com"}{"level":"DEBUG","message":"[2:42:26.4226 PM]: --createStatementPreExec"}
{"level":"DEBUG","message":"[2:42:26.4226 PM]: numBinds = 0"}
{"level":"DEBUG","message":"[2:42:26.4226 PM]: threshold = 65280"}
{"level":"DEBUG","message":"[2:42:26.4226 PM]: RowStatementPreExec"}
{"level":"DEBUG","message":"[2:42:26.4226 PM]: context.bindStage=undefined"}
{"level":"TRACE","message":"[2:42:26.4226 PM]: https://AQA19782.us-east-1.snowflakecomputing.com/queries/v1/query-request?requestId=5add6ea5-b50e-45e7-a867-5abdab8b9fe2"}
{"level":"TRACE","message":"[2:42:26.4226 PM]: Returning OCSP status for certificate 01A1D25F4A87679A7BF8F6387C3E4263 from cache"}
{"level":"TRACE","message":"[2:42:26.4226 PM]: Returning OCSP status for certificate 0773124A4BCBD44EC7B53BEAF194842D3A0FA1 from cache"}
{"level":"TRACE","message":"[2:42:26.4226 PM]: Returning OCSP status for certificate 067F944A2A27CDF3FAC2AE2B01F908EEB9C4C6 from cache"}
{"level":"TRACE","message":"[2:42:26.4226 PM]: Returning OCSP status for certificate A70E4A4C3482B77F from cache"}
{"level":"TRACE","message":"[2:42:26.4226 PM]: socket reused = false"}
{"level":"TRACE","message":"[2:42:26.4226 PM]: OCSP validation succeeded for aqa19782.us-east-1.snowflakecomputing.com"}
row message
row message
row message
...
{"level":"TRACE","message":"[2:42:26.4226 PM]: https://AQA19782.us-east-1.snowflakecomputing.com/session/logout-request"}
{"level":"TRACE","message":"[2:42:26.4226 PM]: Returning OCSP status for certificate 01A1D25F4A87679A7BF8F6387C3E4263 from cache"}
{"level":"TRACE","message":"[2:42:26.4226 PM]: Returning OCSP status for certificate 0773124A4BCBD44EC7B53BEAF194842D3A0FA1 from cache"}
{"level":"TRACE","message":"[2:42:26.4226 PM]: Returning OCSP status for certificate 067F944A2A27CDF3FAC2AE2B01F908EEB9C4C6 from cache"}
{"level":"TRACE","message":"[2:42:26.4226 PM]: Returning OCSP status for certificate A70E4A4C3482B77F from cache"}
{"level":"TRACE","message":"[2:42:26.4226 PM]: socket reused = false"}
{"level":"TRACE","message":"[2:42:26.4226 PM]: OCSP validation succeeded for aqa19782.us-east-1.snowflakecomputing.com"}Sucessfully disconnected.
I want the last word!

6. What did you see instead?
C:\Users\Ed\projects>node myApp.js
(node:11508) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'then' of undefined
    at Connection.connectAsync (C:\Users\Ed\projects\node_modules\snowflake-sdk\lib\connection\connection.js:266:9)
    at kickoff (C:\Users\Ed\projects\myApp.js:21:35)
    at Object.<anonymous> (C:\Users\Ed\projects\myApp.js:18:1)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11508) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:11508) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

7. Add this to get standard output.
 
```
var snowflake = require('snowflake-sdk');
snowflake.configure(
{
  logLevel: 'trace'
});
```

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for raising this issue with us. i think the error
```
node:11508) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'then' of undefined
at Connection.connectAsync (C:\Users\Ed\projects\node_modules\snowflake-sdk\lib\connection\connection.js:266:9)
```

comes due to 2 main reasons:

1. incorrect syntax of `connectAsync`
correct one would be something similar to:
```javascript
connection.connectAsync(
    function (err, conn) {
        console.error('Unable to connect: ' + err);
    }).then(() => {
        var statement = conn.execute({
            sqlText: 'select * from mytable',
            complete: function (err, stmt, rows) {
        
            var stream = stmt.streamRows()
            stream.on('error', err => {
                console.error('Failure:',err.message)
            })
            stream.on('data', row => {
                console.log('row message')
            })
            stream.on('end', () => {
                connection.destroy((err,conn) => {
                    if (err) {
                        console.log('Unable to disconnect from Snowflake:',err.message)
                 }
                    else {
                      console.log('Sucessfully disconnected.')
                 }
                })
            })
           }
        })
    })
```

i.e. you need to handle the returned function from `connectAsync`

2. incorrect usage of `connectAsync`
this method was originally meant to work with the `externalbrowser` authentication, where the caller goes to some identity provider before being able to connect to Snowflake.
Documentation: [Using Single Sign-on (SSO) Through a Web Browser](https://docs.snowflake.com/en/developer-guide/node-js/nodejs-driver-authenticate#using-single-sign-on-sso-through-a-web-browser)

if you don't use the `externalbrowser` authentication, i'm not sure why you would need `connectAsync`. 

hope this helps but please feel free to reopen this issue if you think something is not working as expected.

for the
> // how do I wait for getList to complete before executing the next statement?

part, i think what might be going on here that the console.log is already passed for execution (and thus you see the message immediately) while the rest of the functions are still running, as they take more time. one possible approach might be to make them to return a Promise, and wait until they settle; creating a kinda sequential execution order here. Something like this
```javascript
const snowflake = require('snowflake-sdk')
//snowflake.configure({ logLevel: "trace" })

var myConfig = {
    account: process.env.SFACCOUNT,
    username: process.env.SFUSER,
    password: process.env.SFPASS,
    application: 'Test-GH464',
    database: process.env.SFDB,
    role: process.env.SFROLE,
    schema: process.env.SFSCHEMA,
    warehouse: process.env.SFWH
}
var sfconn = snowflake.createConnection(myConfig)

async function connectToSnoflake(connection) {
    return new Promise( (resolve, reject) => {
        connection.connect( (err, conn) => {
            if (err) {
                reject(err)
            }
            resolve(conn)
        })
    })
}

async function executeQuery(conn) {
    return new Promise( (resolve, reject) => {
        resultset = []
        conn.execute({
            sqlText: 'select * from test464',
            complete: function(err, stmt, rows) {
                if (err) {
                    reject(err)
                }
                for (row of rows) {
                    resultset.push(row)
                }
                resolve(rows)
                console.log(resultset)
            }
        })
    })
}

async function kickoff() {
    connectToSnoflake(sfconn)
     .then( (conn) => executeQuery(conn) )
     .then( (rows) => console.log('I want to have the last word!'))
}

kickoff()
```

Output:
```
$ node --no-warnings testGH464_sync.js 
[ { C1: 1 }, { C1: 2 }, { C1: 3 } ]
I want to have the last word!
```

**Comment by edtguy** [comment]
Thank you. A colleague of mine provided me with a similar solution. I still struggle a bit with asynchronous processing, as I spend most of my time writing SQL, focused on set logic.
Cheers!
