### ISSUE TITLE
Let the connection know what database and schema to use.

### ISSUE THREAD

**Issue by crazyoptimist** [snowflakedb/snowflake-connector-nodejs#483]
## What is the current behavior?

Context is that we run queries across multiple databases and schemas using a single connection.

```js
  const connection = snowflake.createConnection({
    application,
    account,
    username,
    password,
    clientSessionKeepAlive: true,
  });
```
It's very inconvenient to attach database and schema name whenever I compose a sql query.

```js
connection.execute({ sqlText: "SELECT * FROM some_database.some_schema.some_table;" });
```

## What is the desired behavior?

Can we have such functionality that we can set the database and schema name before running a query?

```js
connection.use(databaseName, schemaName);
connection.execute({ sqlText: "SELECT * FROM some_table;" });
```

## How would this improve `snowflake-connector-nodejs`?
It will allow to write less code.

## References, Other Background
It's already behave like that in Snowflake UI, in Worksheets tab(when you write queries there).

## What is your Snowflake account identifier, if any?
Can not disclose

**Comment by sfc-gh-dszmolka** [comment]
hello and thank you for raising this issue. 

if you do not wish to specify the db/schema context for your queries on the `connection`, the preferred way today is what you're already doing, specifying the object's FQDN.

but if you do not wish to do so, the desired functionality is available today, with `snowflake-sdk@1.6.18` and later versions, in the form of [multi-statement queries](https://docs.snowflake.com/en/developer-guide/node-js/nodejs-driver-execute#executing-a-batch-of-sql-statements-multi-statement-support) 
1. first query: issue `use schema dbname.schemaname`
2. second query: issue `select * from table`

you can use either of the 2 approaches described in the above Snowflake documentation to enable multi-statement queries and use them.
