### ISSUE TITLE
Enable `keepAlive` for proxied connections

### ISSUE THREAD

**Issue by jportner** [snowflakedb/snowflake-connector-nodejs#491]
## What is the current behavior?

In #185, the [Agent `keepAlive` option](https://nodejs.org/docs/latest-v14.x/api/http.html#http_new_agent_options) was enabled to improve performance.

However, this package uses `https-proxy-agent` 5.x to send traffic through proxies, which doesn't support `keepAlive`. This means that any consumer who is using Snowflake with a proxy gets a pretty substantial performance hit.

## What is the desired behavior?

`https-proxy-agent` 6.0.0 [added support for keepAlive](https://github.com/TooTallNate/proxy-agents/blob/main/packages/https-proxy-agent/CHANGELOG.md#600).

It would be great to upgrade to that so that proxied connections will use `keepAlive`.

## How would this improve `snowflake-connector-nodejs`?

Performance -- I've benchmarked up to 20x performance improvement when enabling `keepAlive` for proxied connections.

## References, Other Background

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive

## What is your Snowflake account identifier, if any?

`sja11112`

**Comment by jportner** [comment]
I'm putting together a PR to resolve this issue, I'm hoping to have it submitted tomorrow.

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for raising this issue, and especially thank you for the contribution in the PR ! we'll take a look

**Comment by jportner** [comment]
> hi and thank you for raising this issue, and especially thank you for the contribution in the PR ! we'll take a look

Thanks!
I found that the main README mentions how to run the integration tests.
I plan to do revisit the PR next week and run those tests.
In the meantime, I've put the PR back into Draft mode.

**Comment by jportner** [comment]
This was fixed by #641 and #689. Thank you so much!
