### ISSUE TITLE
Add support for MFA token caching

### ISSUE THREAD

**Issue by nathanjcochran** [snowflakedb/snowflake-connector-nodejs#493]
## What is the current behavior?

Every time a new connection is created, a new Duo MFA prompt is triggered. When creating multiple connections in quick succession, this can be very annoying. It is easy to miss one or more of the prompts, which can cause you to be locked out of your account for awhile.

## What is the desired behavior?

The Duo MFA prompt is only triggered for the first connection made in some time window, because the MFA token is cached. Basically, add support for [MFA Token Caching](https://docs.snowflake.com/en/user-guide/security-mfa#using-mfa-token-caching-to-minimize-the-number-of-prompts-during-authentication-optional).

## How would this improve `snowflake-connector-nodejs`?

It would reduce the number of repeated Duo MFA prompts that users have to approve when an application using the node.js snowflake driver makes multiple connections in quick succession.

## References, Other Background

Official documentation on [MFA Token Caching](https://docs.snowflake.com/en/user-guide/security-mfa#using-mfa-token-caching-to-minimize-the-number-of-prompts-during-authentication-optional).

**Comment by sfc-gh-dszmolka** [comment]
hello and thank you for submitting this enhancement request. we'll take a look and i'll try to keep this Issue updated with the news. thank you in advance for bearing with us !

**Comment by john-pavlat** [comment]
+1 on this issue; this would be incredibly helpful for serverless applications.

**Comment by Oracen** [comment]
Quick +1 to this. Is there an approximate ETA on this? Last update was 4 months ago

**Comment by sfc-gh-dszmolka** [comment]
apologies it taking so long, but being an entirely new feature which on top of it, operates on user credentials, we also had to go through a (lengthy) internal security review before the actual implementation. 

Feature PR's can be followed here:
* SSO token cache: #820 
* MFA token cache: #711  (I'll confirm if this is still the proper tracking PR)

As of now, I cannot give a specific ETA for the actual implementation, but syncing internally with the team and will update if there's any more specifics.

**Comment by jonathankkizer** [comment]
Is there an update for this? I see that it missed the April release cycle. Is it likely that it is shipped in the next few months?

**Comment by sfc-gh-dszmolka** [comment]
you can follow the linked PRs for updates. We plan to release this in the upcoming months indeed (there were other priorities so this fell back a bit). Thank you for bearing with us !

**Comment by sfc-gh-dszmolka** [comment]
PR #820 for SSO token caching is now merged, and will be part of the next upcoming release.
We keep working on the MFA token caching #711  too, to be released hopefully at the same time.

**Comment by sfc-gh-dszmolka** [comment]
MFA token caching PR also merged, and both SSO and MFA token caching will be part of the next upcoming release in July 2024.

**Comment by sfc-gh-dszmolka** [comment]
released with Snowflake Node.JS driver v1.12.0 - thank you for bearing with us !
