### ISSUE TITLE
Typescript: 'Parameters' attribute not defined in types definition files when trying to execute a multi-statement SQL query

### ISSUE THREAD

**Issue by dberruezo** [snowflakedb/snowflake-connector-nodejs#494]
Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of NodeJS driver are you using?
1.6.21
   
2. What operating system and processor architecture are you using?
Linux, Kubuntu 23.04, x86_64
   
3. What version of NodeJS are you using?
(`node --version` and `npm --version`)
node v18.15.0 (npm v9.6.4)

4. What are the component versions in the environment (`npm list`)?

├── @commitlint/cli@17.6.3
├── @commitlint/config-conventional@17.6.3
├── @stedi-oss/eslint-plugin-stedi-aws-rules@1.5.2
├── @types/aws-lambda@8.10.115
├── @types/jest@29.5.1
├── @types/snowflake-sdk@1.6.12
├── @types/uuid@9.0.1
├── @typescript-eslint/eslint-plugin@5.59.2
├── @typescript-eslint/parser@5.59.2
├── aws-sdk@2.1373.0
├── dotenv@16.0.3
├── eslint-import-resolver-typescript@3.5.5
├── eslint-plugin-import@2.27.5
├── eslint@8.39.0
├── husky@8.0.3
├── jest@29.5.0
├── serverless-offline@12.0.4
├── serverless@3.30.1
├── snowflake-sdk@1.6.21
├── ts-jest@29.1.0
└── typescript@5.0.4

6.Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```
7. What did you do?

  When using the `execute` method with multi-statement SQL queries the `parameters` attribute provided to the argument object for the method, Typescript would argue `parameters` does not exist in type:

  ```
  connection.execute({
                    sqlText,
                    binds,
                    parameters: { MULTI_STATEMENT_COUNT: 3 },
                    complete: (error: SnowflakeError | null, _: Statement, rows: unknown): void => {
                        if ( error ) {
                            reject(error);
                        } else {
                            resolve(rows);
                        }
                    }
                }
  ```

8. What did you expect to see?

   Since it is shown [here](https://docs.snowflake.com/en/developer-guide/node-js/nodejs-driver-execute#executing-a-batch-of-sql-statements-multi-statement-support) we have to provide a `parameters` attribute with the count of the statements we are providing the method so there should be no issue defining the `parameters` attribute.

  ```
  var selectStatement = connection.execute({
    sqlText: "CREATE OR REPLACE TABLE test(n int); INSERT INTO test values(1), (2); SELECT * FROM test ORDER BY n",
    parameters: { MULTI_STATEMENT_COUNT: 3 },
    complete: function (err, stmt, rows) {
      if (err) {
        console.error('1 Failed to execute statement due to the following error: ' + err.message);
      }
      else {
        console.log('==== complete');
        console.log('==== sqlText=' + stmt.getSqlText());
        if(stmt.hasNext())
        {
          stmt.NextResult();
        }
        else {
          // do something else, e.g. close the connection
        }
      }
    }
  });
  ```

9. Can you set logging to DEBUG and collect the logs?

This is shown by the Visual Studio Code window:

  ```
  Argument of type '{ sqlText: string; binds: (string | number)[]; parameters: { MULTI_STATEMENT_COUNT: number; }; complete: (error: Nullish<SnowflakeError>, _: Statement, rows: unknown) => void; }' is not assignable to parameter of type '{ sqlText: string; streamResult?: boolean | undefined; binds?: Binds | undefined; fetchAsString?: ("String" | "Boolean" | "Number" | "Date" | "JSON" | "Buffer")[] | undefined; complete?: (err: SnowflakeError | undefined, stmt: Statement, rows: any[] | undefined) => void; }'.
    Object literal may only specify known properties, and 'parameters' does not exist in type '{ sqlText: string; streamResult?: boolean | undefined; binds?: Binds | undefined; fetchAsString?: ("String" | "Boolean" | "Number" | "Date" | "JSON" | "Buffer")[] | undefined; complete?: (err: SnowflakeError | undefined, stmt: Statement, rows: any[] | undefined) => void; }'
  ```

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for raising this issue. since it seems to come from `@types/snowflake-sdk` which is not maintained by Snowflake, could you please raise this issue against that repo so the maintainers can get it straightened out ?
thank you in advance!
