### ISSUE TITLE
Allow OCSP Response Cache to only exist in memory

### ISSUE THREAD

**Issue by notkriswagner** [snowflakedb/snowflake-connector-nodejs#50]
One of the customers hit an issue with the latest NodeJS release (1.2.1) where the driver is failing because they are using it in a AWS Lambda job that has a read-only disk. We should allow the OCSP Response Cache to exist purely in memory.

**Comment by nevardreik** [comment]
+1 here

`ERROR	Uncaught Exception	{"errorType":"Error","errorMessage":"EACCES: permission denied, mkdir '/home/sbx_user1051'","code":"EACCES","stack":["Error: EACCES: permission denied, mkdir '/home/sbx_user1051'","    at Object.mkdirSync (fs.js:752:3)","    at sync (/var/task/node_modules/mkdirp/index.js:71:13)","    at sync (/var/task/node_modules/mkdirp/index.js:77:24)","    at Function.sync (/var/task/node_modules/mkdirp/index.js:77:24)","    at Object.exports.mkdirCacheDir (/var/task/node_modules/snowflake-sdk/lib/global_config.js:127:20)","    at new OcspResponseCache (/var/task/node_modules/snowflake-sdk/lib/agent/ocsp_response_cache.js:46:33)","    at getOcspResponseCache (/var/task/node_modules/snowflake-sdk/lib/agent/socket_util.js:42:37)","    at getOcspResonseAndVerify (/var/task/node_modules/snowflake-sdk/lib/agent/socket_util.js:308:24)","    at validateCert (/var/task/node_modules/snowflake-sdk/lib/agent/socket_util.js:351:3)","    at eachCallback (/var/task/node_modules/snowflake-sdk/lib/agent/socket_util.js:217:5)"],"errno":-13,"syscall":"mkdir","path":"/home/sbx_user1051"}`

**Comment by veltman** [comment]
Related: https://github.com/snowflakedb/snowflake-connector-nodejs/issues/51

Assuming the cache is optional, it seems like fixing the `mkdirp` call to fail softly would also address this.

**Comment by nevardreik** [comment]
Changing the cache to use `tmpdir()` resolves the problem. 

```
exports.mkdirCacheDir = function ()
{
  var homeDir = Os.tmpdir();
  var cacheDir;
  const platform = Os.platform();
  if (platform === 'darwin')
  {
    cacheDir = Path.join(homeDir, "Library", "Caches", "Snowflake");
  }
  else if (platform === 'win32')
  {
    cacheDir = Path.join(homeDir, "AppData", "Local", "Snowflake", "Caches");
  }
  else
  {
    // linux
    cacheDir = Path.join(homeDir, ".cache", "snowflake");
  }
  let err = Mkdirp.sync(cacheDir);
  if (err)
  {
    Logger.getInstance().debug("Failed to create a cache directory: %s", err);
  }
  return cacheDir;
};
```

**Comment by smtakeda** [comment]
Working on the fix and mitigation.
