### ISSUE TITLE
XML variant: attribute tags are stripped from the output

### ISSUE THREAD

**Issue by beckjake** [snowflakedb/snowflake-connector-nodejs#506]
Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of NodeJS driver are you using?
`v1.6.22`. This behavior has existed since the introduction of XML parsing.
   
2. What operating system and processor architecture are you using?
 - MacOS 13.4, M1 Pro CPU
   
3. What version of NodeJS are you using?

node: `v18.5.0`
npm: `8.12.1`

4. What are the component versions in the environment (`npm list`)?

```
$ npm list
snowflake-demo@ /Users/jake/tmp/snowflake-demo
└── snowflake-sdk@1.6.22
```

6.Server version
`7.18.1`

7. What did you do?

Create a table with some VARIANT XML data that has attributes. For example:
```xml
<developers company="coolCorp">...</developers>
```

In this xml snippet, `company="coolCorp"` is an attribute of the xml tag `developers`. Then I queried it using the snowflake connector.

Here's a script I wrote to reproduce this, but querying any xml data with attributes is sufficient:
```javascript
const snowflake = require('snowflake-sdk');
const { inspect } = require('util');

// set these in your environment!
const username = process.env.SNOWFLAKE_USERNAME;
const password = process.env.SNOWFLAKE_PASSWORD;
const account = process.env.SNOWFLAKE_ACCOUNT;
const database = process.env.SNOWFLAKE_DATABASE;
const schema = process.env.SNOWFLAKE_SCHEMA || "xmldemo";

/* get a promise for a connected connection object */
const getConnectedConnection = () => {
  return new Promise((resolve, reject) => {
    snowflake.createConnection({account, username, password}).connect((err, conn) => {
      if (err) {
        reject(err);
      } else {
        resolve(conn);
      }
    });
  });
}


/* execute the sql text, returning a promise of the rows */
const execute = (conn, sqlText) => {
  return new Promise((resolve, reject) => {
    const query = {
      sqlText,
      complete: (err, _, rows) => {
        if (err) {
          reject(err);
        } else {
          resolve(rows);
        }
      },
    }
    console.log("executing", sqlText);
    conn.execute(query);
  });
}

const createSchemaStmt = `CREATE SCHEMA IF NOT EXISTS ${database}.${schema}`
const createTableStmt = `CREATE OR REPLACE TABLE ${database}.${schema}.xml_zoo (x OBJECT)`
const insertStmt = `INSERT INTO ${database}.${schema}.xml_zoo (x)
  SELECT PARSE_XML('<exhibit name="Polar Bear Plunge"><animal id="000001"><scientificName>Ursus maritimus</scientificName><englishName>Polar Bear</englishName><name>Kalluk</name></animal><animal id="000002"><scientificName>Ursus maritimus</scientificName><englishName>Polar Bear</englishName><name>Chinook</name></animal></exhibit>')`;
const selectStmt = `SELECT * from ${database}.${schema}.xml_zoo`


const main = async () => {
  snowflake.configure({logLevel: 'trace'});
  const conn = await getConnectedConnection();
  await execute(conn, createSchemaStmt);
  await execute(conn, createTableStmt);
  await execute(conn, insertStmt);
  const rows = await execute(conn, selectStmt);
  for (const row of rows) {
    console.log(inspect(row, { depth: 10 }));
  }
}
main();
```

Output from the query:
```
{
  X: {
    exhibit: {
      animal: [
        {
          scientificName: 'Ursus maritimus',
          englishName: 'Polar Bear',
          name: 'Kalluk'
        },
        {
          scientificName: 'Ursus maritimus',
          englishName: 'Polar Bear',
          name: 'Chinook'
        }
      ]
    }
  }
}
```
As you can see, all the attribute fields have been stripped.

8. What did you expect to see?

I expect to see my attributes somewhere in the xml output, so I can actually round-trip my data. Perhaps something like this, although I am happy with anything I can use to reconstruct the original XML

```
{
  X: {
    exhibit: {
      animal: [
        {
          scientificName: 'Ursus maritimus',
          englishName: 'Polar Bear',
          name: 'Kalluk',
          '@': { id: '000001' }
        },
        {
          scientificName: 'Ursus maritimus',
          englishName: 'Polar Bear',
          name: 'Chinook',
          '@': { id: '000002' }
        }
      ],
      '@': { name: 'Polar Bear Plunge' }
    }
  }
}
```

Having looked into it a bit, I think this is because the XML parser in `lib/result/column.js` is instantiated with the default arguments, and the default behavior of `fast-xml-parser` is to omit attributes entirely - the docs [here](https://github.com/NaturalIntelligence/fast-xml-parser/blob/c7b3cea4ead020c21d39e135a50348208829e971/docs/v4/2.XMLparseOptions.md#ignoreattributes) were helpful to me. On my local fork to experiment with this, I used these parameters to the `XMLParser` constructor, which got me the desired output I showed above:
```
new XMLParser({ignoreAttributes: false, attributesGroupName: '@', attributeNamePrefix: ""});
```

The output of this is generally safe and shouldn't overwrite anything that's valid XML, because `@` isn't a valid entity name in XML, so it should never collide with any actual tags. I think `@` is a pretty common choice for this, too. That said, it really doesn't matter what you choose so long as it does not begin with an alphanumeric character.

Alternatively, some way for users to modify the constructor parameters to the XML parser would be great. As it is though, this feature is losing some pretty useful data.

9. Can you set logging to DEBUG and collect the logs?

I've done this and attached it, though I can't imagine it's going to add anything to your problem solving process.
   
10. What is your Snowflake account identifier, if any? (Optional)

**Comment by sfc-gh-dszmolka** [comment]
#538

**Comment by sfc-gh-dszmolka** [comment]
small update: as a side effect of fixing #528 , the PR #536 (which is now merged) introduces option to configure a custom JSON and XML parser; the latter also comes with the option of initializing it with custom options. Please see [this comment over at issue 528](https://github.com/snowflakedb/snowflake-connector-nodejs/issues/528#issuecomment-1611893260) but also putting _one_ of the configuration options here for the context:

> 3. Configuring the XML parser with the fast-xml-parser module and initialize it with some non-default configuration options (see the module's [XMLparseOptions](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/docs/v4/2.XMLparseOptions.md) for details)
> ```javascript
> const snowflake = require('snowflake-sdk');
> snowflake.configure({
> xmlColumnVariantParser: rawColumnValue => new (require("fast-xml-parser"))
>    .XMLParser({ignoreAttributes: false, attributeNamePrefix: '@', attributesGroupName: null})
>     .parse(rawColumnValue)
> })
> ```

the other option according to the plans will be equipping the XML parser with configuration options, for those users who don't want to set an entire new different parser, just some options for the default `fast-xml-parser` ; the request this issue dealing with originally. It's ongoing on #538

**Comment by beckjake** [comment]
Wow, this is great! thanks!

**Comment by sfc-gh-dszmolka** [comment]
PR #538 is now merged and will be part of the next release, expected towards end of July. This concludes adding the _second_ option to configure XML Parser :) This adds an option to configure 4 of the fast-xml-parser attributes, for use-cases like this, where the whole XML Parser doesn't need to be configured just some of the options. Also working with the Docs team to have this added to the official Snowflake documentation, but will be something like this:

```javascript
const snowflake = require('snowflake-sdk');
snowflake.configure({
  xmlParserConfig: {
    /*  Parameters that you can override
     *   ignoreAttributes - default true,
     *   attributeNamePrefix - default '@',
     *   attributesGroupName - default null,
     *   alwaysCreateTextNode - default false
     */
    ignoreAttributes: false, attributesGroupName: '_'
  }
});
```

(configuration fully independent from the change coming with #536 which would allow for configuring a whole entire XML parser)

**Comment by sfc-gh-dszmolka** [comment]
#567 to fix default values for the new `xmlParserConfig` and make them to match the [default from fast-xml-parser](https://github.com/NaturalIntelligence/fast-xml-parser/blob/v4.2.5/src/xmlparser/OptionsBuilder.js#L2-L41) itself

**Comment by sfc-gh-dszmolka** [comment]
PR is released as part of the latest Snowflake Node.JS driver version 1.7.0. Closing this issue.

**Comment by sfc-gh-dszmolka** [comment]
Releng team hit a bump in the release process which will be continued on Monday as expected. Reopening the issue and will only close when artifact confirmed to published to npm. Apologies for the inconvenience.
