### ISSUE TITLE
Uncaught mkdirp error?

### ISSUE THREAD

**Issue by veltman** [snowflakedb/snowflake-connector-nodejs#51]
If I'm reading it right, I think this block will throw an uncaught error if creating `cacheDir` fails (because of, e.g., a permissions error): https://github.com/snowflakedb/snowflake-connector-nodejs/blob/master/lib/global_config.js#L127-L131

```js
  let err = Mkdirp.sync(cacheDir);
  if (err)
  {
    Logger.getInstance().debug("Failed to create a cache directory: %s", err);
  }
```

`mkdirp.sync` will throw rather than returning the error. It also seems like if it's *successful*, then `err` will be the directory created, so the condition below will be true, and thus log an error message? Am I reading this wrong?

**Comment by smtakeda** [comment]
Yes, this is a known issue. Working in #50

**Comment by smtakeda** [comment]
The error should have been caught. Fixing in #50.
