### ISSUE TITLE
Remove unused dependency "qs"

### ISSUE THREAD

**Issue by sfc-gh-pmotacki** [snowflakedb/snowflake-connector-nodejs#510]
I haven't found any using of dependency qs in driver code. I think we can remove it.

**Comment by sfc-gh-dszmolka** [comment]
apparently came with https://github.com/snowflakedb/snowflake-connector-nodejs/pull/291 but cannot exactly pinpoint why it was added in the first place. I don't think it was ever used in any released version (v1.1.10 and up)
