### ISSUE TITLE
Connect callback not being called

### ISSUE THREAD

**Issue by macnietzsche** [snowflakedb/snowflake-connector-nodejs#531]
Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of NodeJS driver are you using?
v1.6.22

   
2. What operating system and processor architecture are you using?
- MacOS Ventura 13.3.1
- Apple Silicon
   
4. What version of NodeJS are you using?
(`node --version` and `npm --version`)
16.14.2

5. What are the component versions in the environment (`npm list`)?

6.Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```
7. What did you do?

I created a new connection instance with all the necessary information(account, username, password) after I call the connect method no success nor failure message is displayed. The callback function is never called.

```
var connection = snowflake.createConnection({
  account: "myaccount.us-east-2",
  username: "myusername",
  password: "mypassword"
});
```
```
connection.connect( 
    function(err, conn) {
        if (err) {
//Expect to see this log
            console.error('Unable to connect: ' + err.message);
            } 
        else {
//Or this
            console.log('Successfully connected to Snowflake.');
            // Optional: store the connection ID.
            connection_ID = conn.getId();
            }
    }
);
```

8. What did you expect to see?
Either a success or error message.

   What should have happened and what happened instead?

10. Can you set logging to DEBUG and collect the logs?

   https://community.snowflake.com/s/article/How-to-generate-log-file-on-Snowflake-connectors

  e.g
  Add this to get standard output.

```
var snowflake = require('snowflake-sdk');
snowflake.configure(
{
  logLevel: 'trace'
});
```
   
11. What is your Snowflake account identifier, if any? (Optional)

**Comment by sfc-gh-dszmolka** [comment]
hi, i think this is rather a misconfiguration than a driver error. 

i see that your account seems to be (at least per the snippet you shared) in AWS US East (Ohio), 
```javascript
account: "myaccount.us-east-2",
```

and per the Snowflake [Non-VPS Account Locator Formats by Cloud Platform and Region](https://docs.snowflake.com/en/user-guide/admin-account-identifier#format-2-legacy-account-locator-in-a-region) documentation, the correct locator format for such an account is
> If your account locator is xy12345:
>
> Cloud Platform / Region - Account Identifier
> US East (Ohio) / xy12345.us-east-2.aws

so could you please try using
```javascript
account: "myaccount.us-east-2.aws",
```

instead. please let me know in a comment how this went and if further troubleshooting is necessary i'll reopen this for you and continue.

**Comment by macnietzsche** [comment]
> hi, i think this is rather a misconfiguration than a driver error.
> 
> i see that your account seems to be (at least per the snippet you shared) in AWS US East (Ohio),
> 
> ```js
> account: "myaccount.us-east-2",
> ```
> 
> and per the Snowflake [Non-VPS Account Locator Formats by Cloud Platform and Region](https://docs.snowflake.com/en/user-guide/admin-account-identifier#format-2-legacy-account-locator-in-a-region) documentation, the correct locator format for such an account is
> 
> > If your account locator is xy12345:
> > Cloud Platform / Region - Account Identifier
> > US East (Ohio) / xy12345.us-east-2.aws
> 
> so could you please try using
> 
> ```js
> account: "myaccount.us-east-2.aws",
> ```
> 
> instead. please let me know in a comment how this went and if further troubleshooting is necessary i'll reopen this for you and continue.

Thanks for your advice; although I tried what you suggest, I still do not get any error/success message.
This is the only TRACE log I got:
```
{"level":"DEBUG","message":"[10:15:28.1528 AM]: Retry Max sleep time = 16"}
{"level":"DEBUG","message":"[10:15:28.1528 AM]: Contacting SF: /session/v1/login-request?requestId=af25070b-20a3-4357-b9f7-35a7830b69fc&warehouse=COMPUTE_WH&databaseName=PRODUCTION&schemaName=BILLING, (1/5)"}
```

**Comment by sfc-gh-dszmolka** [comment]
okay, let's get a bit more logs about this. created a simple patch file for you based on 1.6.22's `sf.js`, which emits couple of additional loglines, does nothing else:
[sf.js.patch](https://github.com/snowflakedb/snowflake-connector-nodejs/files/11742730/sf.js.patch)

could you please:
1. (optional) take a backup of `snowflake-sdk/lib/services/sf.js`
2. `cd snowflake-sdk/lib/services/` under your `node_modules` directory
3. `patch sf.js < sf.js.patch` to apply the patch to `sf.js` to have more logging (very basic, to the console)
4. add even more http/tls related logging to the `node` runtime and run your script this way
`NODE_DEBUG=http,http2,tls node --no-warnings <yourscript.js>`

and share the output, you might want to edit out sensitive details like account name. If you don't wish to share it here, please open a case with Snowflake Support.

also at this point I would start being suspicious if there's any connectivity issue towards the Snowflake account. you can confirm that with regular tools like `curl` , etc.
