### ISSUE TITLE
Bind variable not set / unexpected '?'

### ISSUE THREAD

**Issue by Bopzor** [snowflakedb/snowflake-connector-nodejs#55]
Hello !

Referring to the [doc](https://docs.snowflake.net/manuals/user-guide/nodejs-driver-use.html#binding-statement-parameters) I need to bind statement parameters but doing it throw me errors and I didn't find the problem.

I'm using `snowflake-sdk v1.2.2` with `node v10.6.1` (and `express v4.17.1`).

Please, look at below examples:  

This works:
```js
const field = 'ColName';

connection.execute({
  sqlText: 'select * from device order by ?',
  binds: [field],
  complete: function(err, stmt, rows) {
    if (err) {
      console.log('Failed to execute statement due to the following error: ' + err.message);
    } else {
      console.log(rows);
    }
  }
});
```

This doesn't work:
```js
const field = 'ColName';

connection.execute({
  sqlText: 'select * from device order by :field',
  binds: [field],
  complete: function(err, stmt, rows) {
    if (err) {
      console.log('Failed to execute statement due to the following error: ' + err.message);
    } else {
      console.log(rows);
    }
  }
});
```
return 
>   Failed to execute statement due to the following error: 
>   SQL compilation error: error line 1 at position 30 Bind variable :field not set.

This doesn't work:
```js
const field = 'ColName';
const sortOrder = 'desc';
const limit = 10;
const offset = 11;

connection.execute({
  sqlText: 'select * from device order by :field :sortOrder limit :limit offset :offset',
  binds: [field, sortOrder, limit, offset], 
  complete: function(err, stmt, rows) {
    if (err) {
      console.log('Failed to execute statement due to the following error: ' + err.message);
    } else {
      console.log(rows);
    }
  }
});
```
return 
>   Failed to execute statement due to the following error: 
>   SQL compilation error: error line 1 at position 30 Bind variable :field not set.

This doesn't work:
```js
const field = 'ColName';
const sortOrder = 'desc';
const limit = 10;
const offset = 11;

connection.execute({
  sqlText: 'select * from device order by ? ? limit ? offset ?',
  binds: [field, sortOrder, limit, offset], 
  complete: function(err, stmt, rows) {
    if (err) {
      console.log('Failed to execute statement due to the following error: ' + err.message);
    } else {
      console.log(rows);
    }
  }
});
```
return
>    Failed to execute statement due to the following error: 
>    SQL compilation error: syntax error line 1 at position 32 unexpected '?'.

For now, the only solution I find to get SQL query like that works, it's to use js template string but it's a security risk I can't keep.

Some more complete doc, working examples or help is very welcome.
Thank's :)

**Comment by smtakeda** [comment]
For column names, can you try `identifier(?)` instead of `?`?

**Comment by Bopzor** [comment]
```js
const field = 'ColName';
const sortOrder = 'desc';
const limit = 10;
const offset = 11;

connection.execute({
  sqlText: 'select * from device order by identifier(?) :sortOrder limit :limit offset :offset',
    binds: [field, sortOrder, limit, offset],
  complete: function(err, stmt, rows) {
    if (err) {
      console.log('Failed to execute statement due to the following error: ' + err.message);
    } else {
      console.log(rows);
    }
  }
});
```
return
>  Failed to execute statement due to the following error: 
SQL compilation error: error line 0 at position -1 invalid identifier '"?"'


```js
const field = 'ColName';
const sortOrder = 'desc';
const limit = 10;
const offset = 11;

connection.execute({
  sqlText: 'select * from device order by identifier(?) ? limit ? offset ?',
    binds: [field, sortOrder, limit, offset],
  complete: function(err, stmt, rows) {
    if (err) {
      console.log('Failed to execute statement due to the following error: ' + err.message);
    } else {
      console.log(rows);
    }
  }
});
```
return
> Failed to execute statement due to the following error: 
SQL compilation error:
syntax error line 1 at position 44 unexpected '?'.
syntax error line 1 at position 41 unexpected '?'.

**Comment by smtakeda** [comment]
hmm, looks like `IDENTIFIER` doesn't work for column name. Also `DESC` cannot be bound.
This is not NodeJS driver issue but the SQL. I cannot do much at this moment.

Can you please reach out the customer support?

**Comment by markandrus** [comment]
@smtakeda I know this is closed, but when you say

> This is not NodeJS driver issue but the SQL.

Do you mean the variable binding is done remotely, in the Snowflake server, and not in the client?

**Comment by smtakeda** [comment]
@markandrus that's correct. Only the Python Connector can bind variables in the client using `%`.
All other drivers bind variables in the server.
