### ISSUE TITLE
SNOW-874337: move from current version of `urllib` (v2)

### ISSUE THREAD

**Issue by sfc-gh-dszmolka** [snowflakedb/snowflake-connector-nodejs#590]
Raising this issue to give a more transparent way to track the internal effort of addressing the current challenges around `urllib` v2.

**Background**:
There already a couple of issues of various severity, stemming from `urllib` v2 (2.40.0) and its direct/indirect dependencies, which `urllib` version is currently in use by the Snowflake Node.JS driver, some examples:

* https://github.com/snowflakedb/snowflake-connector-nodejs/issues/363
* https://github.com/snowflakedb/snowflake-connector-nodejs/issues/454
* https://github.com/snowflakedb/snowflake-connector-nodejs/issues/512
* https://github.com/snowflakedb/snowflake-connector-nodejs/issues/571
(et al)

We cannot just take the `urllib` dependency and bump to the most recent (v3) versions, because `urllib` v3.0.0 introduced a [breaking change](https://github.com/node-modules/urllib/pull/382) as is't been rebased to [undici](https://github.com/nodejs/undici) and that version is incompatible with `snowflake-sdk` implementation today.

As `urllib` provides a core functionality to `snowflake-sdk` (sending HTTP requests to the Snowflake engine) , appropriate care needs to be taken in refactoring the solution.

This Issue is here to track the progress. Current aim is to implement and release the changes by end of Q3 2023

**Comment by StefanTobler** [comment]
Hey there, is there any target date for this fix?

**Comment by sfc-gh-dszmolka** [comment]
yes, apologies for missing it out from the original post. I now added it there, and adding it here too: latest target date is end of Q3 (October). Being a high priority item, we aim for a quicker implementation but that's the current timing.

**Comment by mootari** [comment]
Are you planning to replace urllib with Node-native APIs?

**Comment by sfc-gh-dszmolka** [comment]
as far as I know, there might be multiple approaches on the table still. I'll keep this Issue updated with the details as they become available to the public.

**Comment by sfc-gh-dszmolka** [comment]
after all, as a result of a long consideration and multiple internal discussions, we decided to go with `axios` instead of `urllib` v2 and the change has been merged with https://github.com/snowflakedb/snowflake-connector-nodejs/pull/623 . 

It will be part of the next upcoming release towards end of September.

**Comment by sfc-gh-dszmolka** [comment]
fix is now out with release [1.9.0](https://github.com/snowflakedb/snowflake-connector-nodejs/releases/tag/v1.9.0) , [available on npm](https://www.npmjs.com/package/snowflake-sdk/v/1.9.0) as well
