### ISSUE TITLE
Return Rows as an Array rather than an object

### ISSUE THREAD

**Issue by markddrake** [snowflakedb/snowflake-connector-nodejs#60]
Is there a way to return each row in a result set as an Array rather than an object.

**Comment by smtakeda** [comment]
This is again same as VARIANT binding and fetch support question.

**Comment by markddrake** [comment]
I don’t think you understood me... sorry if I was not clear. This has nothing to do with variant

Assume you have a pure. Relation table with 3 columns and two rows. If I select the content s of the table I will get a result consisting of two objects

{ “col1” : “a”, “col2” :  “b”, “col3” : 1}
{“col1” :  “a2”, “col2”: “b2”, “

**Comment by smtakeda** [comment]
ah ok. Sounds reasonable. We'll add this task to the backlog.
