### ISSUE TITLE
SNOW-894138: AWS JS SDK v3 Support

### ISSUE THREAD

**Issue by jonioni** [snowflakedb/snowflake-connector-nodejs#619]
## What is the current behavior?

The Node.js driver is still using `aws-sdk` (AWS JS SDK v2).

https://github.com/snowflakedb/snowflake-connector-nodejs/blob/dfb780f0f49464b1de15ac01adb5676a73926b22/lib/file_transfer_agent/s3_util.js#L44C2-L44C2

## What is the desired behavior?

Use AWS JS SDK v3 since v2 will be deprecate.

## How would this improve `snowflake-connector-nodejs`?

This keeps the package up to date and works better with Lambda Node.js 18.x (LTS) runtime. Also the modular version of the AWS SDK reduces the size of the package.

## References, Other Background

It seems this was originally implemented (#337) but then reverted (#345).

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for raising this issue ! since the work is already tracked on https://github.com/snowflakedb/snowflake-connector-nodejs/issues/365, i'm closing this as a duplicate.
