### ISSUE TITLE
Support key-based authentication

### ISSUE THREAD

**Issue by casey-largent** [snowflakedb/snowflake-connector-nodejs#62]
Both the Python and Java implementations support the use of Public/Private key pairs. This should be available in this connector as well.

https://docs.snowflake.net/manuals/user-guide/python-connector-example.html#using-key-pair-authentication

https://docs.snowflake.net/manuals/user-guide/jdbc-configure.html#using-key-pair-authentication

**Comment by smtakeda** [comment]
Already in the JIRA but didn't have a chance to implement it.

**Comment by moyuanhuang** [comment]
Hello! Do we have an estimation of when this will be implemented? Or is this not a high priority feature that would like be taken care of in the near future?

**Comment by saidramirez** [comment]
Curious if we could have an update on this issue. I believe that only having plaintext user/password credentials as an authentication method is not very secure.

**Comment by sfc-gh-kwagner** [comment]
We are working on external browser authentication support with key-pair auth to follow soon afterwards. External browser auth should be released within the next two releases. We don't have a firm timeline on when key-pair auth is going to be released. But I will update here when there we have a better idea.

(of course timelines are subject to change)

**Comment by jacobworrel** [comment]
Looks like the latest version support key pair auth: https://docs.snowflake.com/en/user-guide/nodejs-driver-use.html#using-key-pair-authentication-key-pair-rotation

**Comment by saidramirez** [comment]
Thanks for the follow up!

**Comment by sfc-gh-dszmolka** [comment]
keypair authentication support released with v1.6.0, thank you for your patience
