### ISSUE TITLE
SNOW-906755: Warnings about Deprecated Packages

### ISSUE THREAD

**Issue by awhitford** [snowflakedb/snowflake-connector-nodejs#629]
The following warnings were generated by installing `snowflake-sdk`:
```
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
 WARN  deprecated string-similarity@4.0.4: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
 WARN  deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
```

1. What version of NodeJS driver are you using?
1.8.0
   
2. What operating system and processor architecture are you using?
Mac OS 13.5.1
   
3. What version of NodeJS are you using?
node: 20.5.1
pnpm: 8.6.12

4. What are the component versions in the environment (`npm list`)?
```
dependencies:
flowbite 1.8.1
lucide-solid 0.274.0
snowflake-sdk 1.8.0
solid-js 1.7.11

devDependencies:
autoprefixer 10.4.15
postcss 8.4.29
solid-devtools 0.27.7
tailwindcss 3.3.3
typescript 5.2.2
vite 4.4.9
vite-plugin-solid 2.7.0
```

5. Server version:
n/a

6. What did you do?
`pnpm i snowflake-sdk`

7. What did you expect to see?
No warnings.

8. Can you set logging to DEBUG and collect the logs?
n/a
   
9. What is your Snowflake account identifier, if any? (Optional)
n/a

**Comment by awhitford** [comment]
Related to #259

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for raising this issue. You're right, the `uuid` deprecation is already planned to be addressed.

The `querystring` one should be automatically go away after the upgrade to AWS SDK v3 is done (https://github.com/snowflakedb/snowflake-connector-nodejs/pull/616) as the deprecated package seems to be an indirect dependency, coming from `aws-sdk` v2.

Finally for the `string-similarity` one, we'll take a look and see how best to address it.

**Comment by sfc-gh-dszmolka** [comment]
`uuid` resolved with https://github.com/snowflakedb/snowflake-connector-nodejs/pull/637

**Comment by alhassanbilkent** [comment]
When should we expect the NPM package to be updated to include the AWS v3 fix?

**Comment by sfc-gh-dszmolka** [comment]
for AWS SDK v3, please see https://github.com/snowflakedb/snowflake-connector-nodejs/issues/365#issuecomment-1720864436 . It's already merged, so will be available with the next version of the driver; towards end of September.

**Comment by sfc-gh-dszmolka** [comment]
node.js driver version 1.9.1 released with the fix and is available on npm. thank you all for bearing with us !
