### ISSUE TITLE
Upgrade https-proxy-agent dependency

### ISSUE THREAD

**Issue by electrovir** [snowflakedb/snowflake-connector-nodejs#63]
`https-proxy-agent` has a high security vulnerability (https://www.npmjs.com/advisories/1184) and should be upgraded to >=3.0.0

https://github.com/snowflakedb/snowflake-connector-nodejs/blob/673eb5049a343805799cc2be4b49968d41248e41/package.json#L14

**Comment by notkriswagner** [comment]
@electrovir Thanks for the heads up. I'll update package.json accordingly

**Comment by ankit-bhatnagar167** [comment]
Fixed in Release v1.3.2
