### ISSUE TITLE
SNOW-922989: The bignumber.js floor function has been removed in versions >= 6.0

### ISSUE THREAD

**Issue by mblakley** [snowflakedb/snowflake-connector-nodejs#648]
1. What version of NodeJS driver are you using?
v1.7.0
   
2. What operating system and processor architecture are you using?
Linux - Debian Stretch AMD64 (node:14.18.1 container from docker hub)
   
3. What version of NodeJS are you using?
v14.18.1

4. What are the component versions in the environment (`npm list`)?
Relevant dependency is bignumber.js, latest version is 9.x, but this issue exists when using any bignumber.js version >= 6.0

5.Server version:
7.33.1

6. What did you do?

Calling the `convertRawTimestampTz` function while pulling in a bignumber.js dependency with a version >= 6.0.0 results in the error:
```
/home/node/app/node_modules/snowflake-sdk/lib/connection/result/column.js:527
  var valSecBig = epochFracSecsBig.dividedBy(scaleFactor).floor();
                                                          ^
TypeError: epochFracSecsBig.dividedBy(...).floor is not a function
    at convertRawTimestampHelper (/home/node/app/node_modules/snowflake-sdk/lib/connection/result/column.js:527:59)
    at Object.convertRawTimestampNtz [as convert] (/home/node/app/node_modules/snowflake-sdk/lib/connection/result/column.js:419:10)
    at Column.extractFromRow (/home/node/app/node_modules/snowflake-sdk/lib/connection/result/column.js:774:19)
    at Column.getRowValue (/home/node/app/node_modules/snowflake-sdk/lib/connection/result/column.js:235:27)
    at Object.getColumnValue (/home/node/app/node_modules/snowflake-sdk/lib/connection/result/chunk.js:350:28)
    at externalizeRow (/home/node/app/node_modules/snowflake-sdk/lib/connection/result/row_stream.js:445:84)
    at /home/node/app/node_modules/snowflake-sdk/lib/connection/result/row_stream.js:190:26
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```
Release notes from bignumber.js show that the floor function was removed in version 6.0.0: https://github.com/MikeMcl/bignumber.js/blob/6f2932fe5b41e0a2a037ae3004d6562a68c70cff/CHANGELOG.md?plain=1#L113
The expected code changes to replace any calls to the floor function can be found here: https://github.com/MikeMcl/bignumber.js/issues/139#issuecomment-361758736

7. What did you expect to see?
Expected to see the bignumber object rounded down (the functionality that the floor() function should provide)

8. Can you set logging to DEBUG and collect the logs?
Not necessary, as this is a syntax/object usage error
   
9. What is your Snowflake account identifier, if any? (Optional)

**Comment by mblakley-cb** [comment]
Thank you for reviewing!  Another possible solution would be to set an upper bound on the bignumber.js version in package.json - my initial thought was that my proposed solution would allow moving to the newest versions of that package instead of sticking with the older versions.

**Comment by sfc-gh-dszmolka** [comment]
We're checking how to best approach this. Perhaps bump `bignumber.js` all the way up if we're already upgrading it, and not stop at the 2018 version 6.0.0. Will keep this issue posted.

**Comment by mblakley** [comment]
The only reason I chose v6.0 is because that's where the `floor` function got removed.  Every version past that should be compatible with how `snowflake-connector-nodejs` is using it, so bumping up to the latest version should certainly work if you choose to do that.  I appreciate your time, and please let me know if there's anything I can do to help!

**Comment by sfc-gh-dszmolka** [comment]
I see PR https://github.com/snowflakedb/snowflake-connector-nodejs/pull/649 is merged now and thus will be part of the October release, expected towards the end of the month. Thank you for your contribution !

**Comment by sfc-gh-dszmolka** [comment]
node.js driver version 1.9.1 released with the fix and is available on npm. thank you all for bearing with us !
