### ISSUE TITLE
SNOW-926514: Missing release notes for 1.9.0

### ISSUE THREAD

**Issue by haggholm** [snowflakedb/snowflake-connector-nodejs#655]
As the title says—the GitHub release notes for the latest version (1.9.0) points to the [community page](https://community.snowflake.com/s/article/Node-js-Driver-Release-Notes), but that page only has notes up through 1.8.0.

**Comment by sfc-gh-dszmolka** [comment]
hello and thank you for submitting this issue, we know it's missing and apologize for not being able to publish it in a timely manner right next to the release time. i'll update this issue once it's out.

**Comment by sfc-gh-mheavin** [comment]
As mentioned on the https://community.snowflake.com/s/article/Snowflake-Connector-and-Driver-Release-Notes page, release notes are now published solely in the documentation site (https://docs.snowflake.com/en/release-notes/clients-drivers/monthly-releases). The monthly update for node.js is at https://docs.snowflake.com/en/release-notes/clients-drivers/nodejs-2023 (until 2024).

**Comment by sfc-gh-dszmolka** [comment]
thanks @sfc-gh-mheavin - closing this issue since release notes are available.
