### ISSUE TITLE
SNOW-937422: Snowflake SDK in combination with lambda results in handlers timing out

### ISSUE THREAD

**Issue by qwertykg** [snowflakedb/snowflake-connector-nodejs#666]
1. What version of NodeJS driver are you using?
I am using 1.9.0 but also tried 1.6.17 and the issue persisted
   
2. What operating system and processor architecture are you using?
Lambda node.js 18.x on both arm and x86 architectures
   
3. What version of NodeJS are you using?
nodejs18.x - the version available on aws lambda
(`node --version` and `npm --version`)

4. What are the component versions in the environment (`npm list`)?
├── @types/snowflake-sdk@1.6.14
├── fork-ts-checker-webpack-plugin@9.0.0
├── snowflake-sdk@1.9.0
├── ts-loader@9.5.0
├── webpack-cli@5.1.4
└── webpack@5.88.2

5.Server version:* E.g. 1.90.1
My issue with with version 1.9.0 of the js snowflake-sdk
6. What did you do?
i am trying to run the snowflake-sdk on aws lambda using the NodeJS runtime. My lambda function works fine but as soon as I import snowflake-sdk and try to use it, then my lambda function starts timing out and does not execute. I was able to create a minimal lambda handler here:

```js
import { createConnection } from "snowflake-sdk";

export const handler = async (event: any): Promise<void> => {
    console.log("hi" );
    console.log(createConnection);
};
```

Building the above code into js and using the compiled js in lambda causes the following error:

![image](https://github.com/snowflakedb/snowflake-connector-nodejs/assets/17964124/9e63c4c5-a02c-4d50-9049-1e306d33dd88)

It times out after three seconds because the lambda function is set to timeout if it stalls for three seconds. Raising this number just increases how long it stalls for before timing out.

My tsconfig can be seen here:

```json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "commonjs",
    "sourceMap": true,
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "moduleResolution": "Node",
    "noEmit": false
  },
  "exclude": [
    "**/*.test.ts"
  ]
}
```
Removing all references to snowflake-sdk causes the lambda function to work fine.

7. What did you expect to see?
I don't seem to have done anything out of the ordinary, so was expecting the lambda to atleast run even if there are errors. The timeout is unexpected

8. Can you set logging to DEBUG and collect the logs?
I'm not getting far enough for logs to be generated

9. What is your Snowflake account identifier, if any? (Optional)
N/A

**Comment by qwertykg** [comment]
I was able to test this locally using node 18 and it works fine. If you're having trouble reproducing this I can upload my demo template to git and send a link? You would need to use your own aws credentials to deploy tho :)

**Comment by sfc-gh-dszmolka** [comment]
well if it would be not too much of a hassle to provide a reproducible scenario alongside with the environment setup, that might be very helpful indeed and thank you in advance ! I'm curious to test whether this can be anyhow related to 407 (and if the same solution applies)

**Comment by qwertykg** [comment]
So I actually got to the bottom of it, it was an interesting one. Basically the way I built my typescript into javascript wasn't playing nicely with snowflake and AWS lambda :/ And it seemed to only be broken on my M2 Macbook pro. Windows users were fine for some reason. It was also broken on AWS itself so maybe its a problem in UNIX systems?

Regardless, I found a way of building that works for mac and windows. I had to use the aws-sam-webpack-plugin (https://www.npmjs.com/package/aws-sam-webpack-plugin). 

Once I was using that library to build my ts in js then it magically worked :/ 

I still dont actually know if its primarily a webpack problem, or a AWS lambda problem or a problem with the snowflake SDK. But I setup a repository if you want to test this out: https://gitlab.com/qwertykg/lambda-ts-demo

You can read the README for a setup guide, and how to reproduce the issue :)

I will leave this open incase you wish to investigate further, but from my side this is resolved. And if you wish you can close it :)

**Comment by sfc-gh-dszmolka** [comment]
thank you so much for preparing and sharing this detailed reproduction and solution as well ! This way if anyone else stumbles into the same issue, they can use your solution to proceed. 
For now since there is no evidence the issue stems from `snowflake-sdk` (which is, I would like to add, is primarily meant to be used under `node.js`, hence the name: Snowflake Node.JS driver :) ), so marking this one as closed.

Of course if new information becomes available which hints towards the issue with the driver, we can always continue.

Again would like to thank you for the details and contribution!
