### ISSUE TITLE
SNOW-992395: The lib leaks keepalive sockets when uploading files + using S3 client

### ISSUE THREAD

**Issue by GabrielLomba** [snowflakedb/snowflake-connector-nodejs#734]
Hi! I have a service running that uploads lots of files to a Snowflake stage to then insert the data into tables. The problem, however, is that there is a memory leak created by how the Snowflake SDK uses AWS S3 clients. There are many places where the SDK creates temporary clients (to name a few: [here](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/49d0e7bfc1a919334e22b6e9df75a5ff953f3beb/lib/file_transfer_agent/file_transfer_agent.js#L136), [here](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/49d0e7bfc1a919334e22b6e9df75a5ff953f3beb/lib/file_transfer_agent/file_transfer_agent.js#L299) and [here](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/49d0e7bfc1a919334e22b6e9df75a5ff953f3beb/lib/file_transfer_agent/s3_util.js#L117)) but the SDK never calls `client.destroy()` on them (defined in the AWS SDK [here](https://github.com/aws/aws-sdk-js-v3/blob/ad9fb3c116e684a00e4526eb65869939c99c5c4d/clients/client-s3/src/S3Client.ts#L808)).

Each S3 client creates a http agent with keepalive sockets and those are just never destroyed, creating increasing memory usage over the time. While [Node docs](https://nodejs.org/api/http.html#agentdestroy) state that destroying an agent is usually not needed, for keepalive sockets (this case), it's best to do it explicitly and, in our experience, keepalive sockets pointing at AWS infrastructure stay alive for a really long time, enough to cause increasing memory usage.

I also noticed the SDK creates clients (for instance, [here](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/49d0e7bfc1a919334e22b6e9df75a5ff953f3beb/lib/file_transfer_agent/file_transfer_agent.js#L139)) and set them in `meta` but they're never reused in the respective util files when they could. [PR to fix this](https://github.com/snowflakedb/snowflake-connector-nodejs/pull/735) has been created.

1. What version of NodeJS driver are you using?
v1.9.0
   
2. What operating system and processor architecture are you using?
Ubuntu, x86_64
   
3. What version of NodeJS are you using?
v14.19.0

4. What are the component versions in the environment (`npm list`)?
NA

5. Server version:* E.g. 1.90.1
NA

6. What did you do?
My service uploads lots of data files to Snowflake stage which is then inserted into tables.

7. What did you expect to see?
Controlled memory usage over a greater period of time.

9. What is your Snowflake account identifier, if any? (Optional)
NA

**Comment by sfc-gh-pmotacki** [comment]
Thank you @GabrielLomba. It looks like a bug in our our sdk. I will take a look on your PR and add fix to next version.

**Comment by sfc-gh-dszmolka** [comment]
checked why this issue was closed; apparently its PR was released in snowflake-sdk 1.9.3

**Comment by GabrielLomba** [comment]
@sfc-gh-pmotacki , I see the changes related to this issue were reverted in PR #747 (both client reuse and destruction) and are not present in the latest SDK version. The PR does not have any description so I have no idea why that was necessary. Can we reopen the issue in that case? Since the memory leak described still exists.
