### ISSUE TITLE
SNOW-1230605: Easy logging garbage in std out make it unusable 

### ISSUE THREAD

**Issue by velocityzen** [snowflakedb/snowflake-connector-nodejs#794]
1. What version of NodeJS driver are you using?
1.10.0
   
2. What operating system and processor architecture are you using?
macOS, linux
   
3. What version of NodeJS are you using?
(`node --version` and `npm --version`)
20.11.1

4. What are the component versions in the environment (`npm list`)?
what component? 

5.Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```
6. What did you do?

Every time I start my application I have this output: 

```
(node:46590) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
{"level":"INFO","message":"[9:48:23.841 AM]: Trying to initialize Easy Logging"}
{"level":"INFO","message":"[9:48:23.846 AM]: No client config file found in default directories"}
{"level":"INFO","message":"[9:48:23.846 AM]: Easy Logging is disabled as no config has been found"}
```

it makes stdOut completely unusable.

7. What did you expect to see?

nothing

**Comment by sfc-gh-dszmolka** [comment]
hi, would setting `snowflake.configure({ logLevel: "WARN" });` help you perhaps ?

**Comment by KalSzeAvaxia** [comment]
How do we configure this "easy logging" thing to begin with? I don't think I see anything in the documentation.

**Comment by cleve-fauna** [comment]
Its pretty annoying. Could we get that default out of there?

**Comment by sfc-gh-dszmolka** [comment]
thanks folks for all this feedback. will try to address it in https://github.com/snowflakedb/snowflake-connector-nodejs/pull/886

**Comment by sfc-gh-dszmolka** [comment]
TIL from https://github.com/snowflakedb/snowflake-connector-nodejs/pull/886#discussion_r1716821760 that logging EasyLogging messages on `INFO` level is a request from Snowflake Security team for compliance, and I'm not allowed to change it to `DEBUG`. So it stays on `INFO` apparently, apologies everyone.

If it's disturbing, please set a higher general loglevel or turn it `OFF` , see https://github.com/snowflakedb/snowflake-connector-nodejs/issues/794#issuecomment-1991736326

**Comment by bcardiff** [comment]
I'm facing this issue, but even if I do 

```js
snowflake.configure({
  logLevel: "OFF",
  additionalLogToConsole: false
})
```

I still see one log entry in the stdout.

```
{"level":"INFO","message":"[5:29:46.973 PM]: Configuring logger with level: -1, filePath: undefined, additionalLogToConsole: false"}
```

Is there a way to turn off all the logging? The process I'm working on needs to be in total control of what it is sent to stdout.
