### ISSUE TITLE
SNOW-141055: Test script missing from repository

### ISSUE THREAD

**Issue by smbkr** [snowflakedb/snowflake-connector-nodejs#83]
4. What did you do?
* Clone current master branch
* Install dependencies
* Run `npm test`

5. What did you expect to see?
The tests should run

6. What did you see instead?
`sh: ./scripts/run_test.sh: No such file or directory`

---

I'd like to start contribution to this module, however without being able to get started running the tests easily, it's a bit of a blocker. 

I tried running the tests manually with `./node_modules/.bin/mocha 'test/**/*.js'` but this throws an error (`Error [MissingParameterError]: A user name must be specified.`). I tried creating `~/parameters.json` as described in `README.rst` but this didn't help. I guess that the `run_test.sh` script does some setup.

I'd find it helpful as well if the readme had some more info here on what exactly this config expects, and what kind of Snowflake env I need to set up locally. Can I use docker for instance to run the tests? In that case, what about including a Dockerfile for development so that newcomers to the project can get up and running easily?

**Comment by maulikdoshi82** [comment]
No response on this one yet?

**Comment by golergka** [comment]
I'd love to contribute, but the fact that this issue is still open without reply 1,5 years later suggests that outside contributions aren't welcome.

**Comment by golergka** [comment]
Why have this issue been closed?
