### ISSUE TITLE
SNOW-1372895: Update the copyright date.

### ISSUE THREAD

**Issue by sfc-gh-ext-simba-jy** [snowflakedb/snowflake-connector-nodejs#839]
## What is the current behavior?
The copyright date in the driver is already expired.

## What is the desired behavior?
Update the date..

**Comment by sfc-gh-ext-simba-jy** [comment]
https://github.com/snowflakedb/snowflake-connector-nodejs/pull/810

**Comment by sfc-gh-dszmolka** [comment]
(Issue to track PR)

**Comment by sfc-gh-dszmolka** [comment]
released with May 2024 release cycle, version 1.11.0
