### ISSUE TITLE
SNOW-141056: Code formatting script not readily usable

### ISSUE THREAD

**Issue by smbkr** [snowflakedb/snowflake-connector-nodejs#84]
4. What did you do?
Tried running the code formatting script in `README.rst`:
`format.sh -mask "*.js" -settings $(pwd)/webstorm-codestyle.xml -R $(pwd)/lib/ -R $(pwd)/test -R $(pwd)/system_test`

First I had to change the path to the script since it's at `scripts/format_code.sh` not `format.sh`, however this still fails as it assumes the user has a file located at `~/WebStorm/bin/format.sh` to do the formatting.

5. What did you expect to see?
Code to be reformatted

6. What did you see instead?
`./scripts/format_code.sh: line 4: /Users/smbkr/WebStorm/bin/format.sh: No such file or directory`

---

I'd strongly suggest using a well supported tool like Prettier here. This would make it easier for people who want to add contributions (such as myself!) to start working on the project.

**Comment by sfc-gh-dszmolka** [comment]
i'll close this abandoned issue now, i think it should be resolved with https://github.com/snowflakedb/snowflake-connector-nodejs/pull/544
