### ISSUE TITLE
SNOW-1439400: Fix the typos in the node.js driver.

### ISSUE THREAD

**Issue by sfc-gh-ext-simba-jy** [snowflakedb/snowflake-connector-nodejs#841]
## What is the current behavior?
There are some typos.
## How would this improve `snowflake-connector-nodejs`?
Yes

**Comment by sfc-gh-dszmolka** [comment]
fixed by https://github.com/snowflakedb/snowflake-connector-nodejs/pull/836

**Comment by sfc-gh-dszmolka** [comment]
released with May 2024 release cycle, version 1.11.0
