### ISSUE TITLE
SNOW-1441259: Add clientConfigFile to ConnectionOptions type

### ISSUE THREAD

**Issue by ldaijiw** [snowflakedb/snowflake-connector-nodejs#842]
## What is the current behavior?
With typescript, When using `createConnection` or `createPool` and following the [documentation](https://docs.snowflake.com/developer-guide/node-js/nodejs-driver-logs#use-easy-logging-while-debugging-your-code) for easy logging, adding the `clientConfigFile` connection parameter raises a type error.

> Object literal may only specify known properties, and 'clientConfigFile' does not exist in type 'ConnectionOptions'.

## What is the desired behavior?

As per the connection options [documented](https://docs.snowflake.com/en/developer-guide/node-js/nodejs-driver-options#label-nodejs-addl-options), `clientConfigFile` should be added to the ConnectionOptions type so that it can be used in typescript

## How would this improve `snowflake-connector-nodejs`?

Improved typing

**Comment by sfc-gh-dszmolka** [comment]
hi - apparently we indeed missed this; thank you for adding it in https://github.com/snowflakedb/snowflake-connector-nodejs/pull/843 and so quickly , literally hours after the typings were merged ;)
