### ISSUE TITLE
SNOW-146028: API key for 3rd party platforms accessing Snowflake

### ISSUE THREAD

**Issue by flashtheman** [snowflakedb/snowflake-connector-nodejs#86]
1. What version of NodeJS are you using (`node --version` and `npm --version`)?
12.16.1

2. What operating system and processor architecture are you using?
Arch Linux 

5. What did you expect to see?
I would like my users to be able to enter the snowflake credentials (account, username and password) on my platform in order for my platform to execute statements on my customer's snowflake environment. Currently I don't see an alternative to saving the user's password in my environment. I really want to avoid this. ClientSessionKeepAlive seems not to be an option as the connection gets lost on service restarts. At least this is how I understand it.

6. What did you see instead?
I would like to see a way of solving my problem - e.g. by retrieving an API key from snowflake if a customer connects to snowflake once. I could then save this API key which may be valid for e.g. 6 months.

**Comment by sfc-gh-dszmolka** [comment]
i'm not sure this quesion was in the right place here originally, could explain the total lack of responses in such a long time :( sorry to see that.
`clientSessionKeepAlive` is surely not the right solution as it would just send keepalive pings/queries to the underlying Snowflake platform and does not work as an intermediate configurable layer of saving credentials outside of Snowflake. hope you found the answer in the meantime.
