### ISSUE TITLE
SNOW-1508219: In type of StatementOption, `complete` should be optional

### ISSUE THREAD

**Issue by etienne-collibra** [snowflakedb/snowflake-connector-nodejs#860]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `snowflake-sdk@1.11.0` for the project I'm working on.

After upgrading to `1.11.0` I got a type error cause by a missing `complete` callback. This callback was optional in `@types/snowflake-sdk` ([link](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/snowflake-sdk/index.d.ts#L608)). Looking at [the code](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/8f0b0f65e1db163432e4b6de9e2a431041e7f95e/lib/connection/statement.js#L604-L606) the callback seems indeed optional.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/snowflake-sdk/index.d.ts b/node_modules/snowflake-sdk/index.d.ts
index 7d494f7..3d5ce77 100644
--- a/node_modules/snowflake-sdk/index.d.ts
+++ b/node_modules/snowflake-sdk/index.d.ts
@@ -491,7 +491,7 @@ declare module 'snowflake-sdk' {
 
     export interface StatementOption {
         sqlText: string;
-        complete: StatementCallback;
+        complete?: StatementCallback;
 
         /**
          * The requestId is for resubmitting requests.
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by sfc-gh-dszmolka** [comment]
hi - thank you for the detailed error description! indeed looks to be optional and apparently wasn't addressed in https://github.com/snowflakedb/snowflake-connector-nodejs/pull/851 either.  we'll look.

**Comment by sfc-gh-dszmolka** [comment]
https://github.com/snowflakedb/snowflake-connector-nodejs/pull/861

**Comment by sfc-gh-dszmolka** [comment]
fix is now merged and will be part of the next release. Thank you again for your contribution!

**Comment by sfc-gh-dszmolka** [comment]
released with Snowflake Node.JS driver v1.12.0
