### ISSUE TITLE
SNOW-147513: Update agent-base

### ISSUE THREAD

**Issue by noahw3** [snowflakedb/snowflake-connector-nodejs#88]
There are well documented issues with `agent-base` leaking memory (https://github.com/TooTallNate/node-agent-base/issues/22). These were fixed in version 4.3.

This project is still on 2.1, so anyone pulling in `snowflake-sdk` as a dependency also takes on this memory leak.

Current version of `agent-base` is 6.0.

**Comment by sfc-gh-kterada** [comment]
Thank you for submitting this issue, @noawh3.

We will circle back once timelines around getting the current project dependency on the `agent-base` library to a version containing a fix for https://github.com/TooTallNate/node-agent-base/issues/22 are determined.

**Comment by sfc-gh-dszmolka** [comment]
closing issue based on the previous comment
