### ISSUE TITLE
SNOW-1621414: Update fast-xml-parser package to v4.4.1 to Fix ReDOS Vulnerability

### ISSUE THREAD

**Issue by GOPIKRISHNA11596** [snowflakedb/snowflake-connector-nodejs#885]
## What is the current behavior?
Currently Snowflake-SDK using the "fast-xml-parser" version of "^4.2.5", But version below 4.4.1 is having ReDOS vulnerability. https://github.com/advisories/GHSA-mpg4-rc92-vx8v 

## What is the desired behavior?
To fix ReDOS vulnerability, need to update "fast-xml-parser" to "^4.4.1"

## How would this improve `snowflake-connector-nodejs`?
It fixes ReDOS vulnerability

## References, Other Background
Please go through link for more info,
Vulnerability : https://github.com/advisories/GHSA-mpg4-rc92-vx8v

**Comment by sfc-gh-dszmolka** [comment]
thank you for keeping a keen eye for vulnerabilities ! fortunately this doesn't affect snowflake-sdk.
requirement of `"fast-xml-parser": "^4.2.5",` means 'install the latest which is at least 4.2.5, but no greater or equal to 5.0.0' ([docs](https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004))

so fixed fast-xml-parses is automatically installed when you (re)install snowflake-sdk. simple test:
```
# npm i snowflake-sdk
..gets installed
# npm list fast-xml-parser
test@ /test
`-- snowflake-sdk@1.12.0
  +-- @aws-sdk/client-s3@3.627.0
  | `-- @aws-sdk/core@3.624.0
  |   `-- fast-xml-parser@4.4.1 deduped
  +-- @google-cloud/storage@7.12.1
  | `-- fast-xml-parser@4.4.1 deduped
  `-- fast-xml-parser@4.4.1.  <<<<< this is the fixed version which is installed automatically
```

closing this issue for now but if you found something different and have evidence that upon install, a vulnerable version of fast-xml-parser is installed, comment here please and i'll look.
