### ISSUE TITLE
SNOW-1649421: Compile error with `index.d.ts`

### ISSUE THREAD

**Issue by weiwong** [snowflakedb/snowflake-connector-nodejs#902]
[This PR](https://github.com/snowflakedb/snowflake-connector-nodejs/pull/890/files#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8R85-R89) included semicolons to delimit enum entries for `ErrorCode` instead of commas, resulting in the following compile error:

```
node_modules/snowflake-sdk/index.d.ts:85:66 - error TS1357: An enum member name must be followed by a ',', '=', or '}'.

85         ERR_CONN_CREATE_INVALID_CLIENT_REQUEST_MFA_TOKEN = 404052;
```

**Comment by sfc-gh-dszmolka** [comment]
thank you for raising this. created https://github.com/snowflakedb/snowflake-connector-nodejs/pull/903 and discussing with the team how we could release a patch (given we literally released a new version hours ago)

we need better tests for this 🤦

**Comment by huypham50** [comment]
Same issue, thanks for introducing me to this article https://maxleiter.com/blog/pin-dependencies

**Comment by sfc-gh-dszmolka** [comment]
fix is merged now and we're working on releasing a patch as soon as possible. apologies for the inconvenience caused.

**Comment by sfc-gh-dszmolka** [comment]
version 1.13.1 released couple hours ago with the fix.
