### ISSUE TITLE
SNOW-1658878: Unhandled Rejection at Promise The "callback" argument must be of type function. Received undefined

### ISSUE THREAD

**Issue by ZeRego** [snowflakedb/snowflake-connector-nodejs#907]
Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of NodeJS driver are you using?

~1.10.0 in package.json
1.10.1 in package-lock.json
   
3. What operating system and processor architecture are you using?

linux/amd64
   
4. What version of NodeJS are you using?
(`node --version` and `npm --version`)

v20.14.0
10.7.0

5. What are the component versions in the environment (`npm list`)?

snowflake-sdk@1.10.1

6. Server version:* E.g. 1.90.1

 n/a

7. What did you do?

   If possible, provide a recipe for reproducing the error.
   A complete runnable program is good.

Issue happening to a user. Haven't been able to reproduce with our credentials.

You can inspect how we are using the client in our repo: https://github.com/lightdash/lightdash/blob/main/packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

We get the error:

```
Unhandled Rejection at Promise The "callback" argument must be of type function. Received undefined
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at /usr/app/node_modules/snowflake-sdk/lib/http/base.js:47:19
at Object.callback (/usr/app/node_modules/snowflake-sdk/lib/services/sf.js:639:43)
at Timeout.requestCallback (/usr/app/node_modules/snowflake-sdk/lib/services/sf.js:1148:23)
at Object.callback (/usr/app/node_modules/snowflake-sdk/lib/connection/connection.js:177:26)
at setInterval (node:timers:209:3)
```

I looked into your code and looks like you are not passing the `callback` as an argument for `self.heartbeat `
https://github.com/snowflakedb/snowflake-connector-nodejs/blame/master/lib/connection/connection.js#L179

Looks like this bug was introduced in this PR: https://github.com/snowflakedb/snowflake-connector-nodejs/pull/502

9. What did you expect to see?

   What should have happened and what happened instead?

No error.

10. Can you set logging to DEBUG and collect the logs?

Will provide later

**Comment by sfc-gh-dszmolka** [comment]
hello and thank you for reporting this issue and also the PR proposal ! i see you also reported this issue in case 00843932 - to avoid duplicated efforts, please work with your support engineer assigned to the support case you raised. I'm now marking this ticket as closed.

**Comment by sfc-gh-dszmolka** [comment]
reopening to properly keep track with release cycle

**Comment by sfc-gh-dszmolka** [comment]
released with Snowflake Node.js driver version 1.14.0 in September 2024 release cycle
