### ISSUE TITLE
SNOW-1726666: Spurious and Unwanted Log message generated by snowflake-sdk

### ISSUE THREAD

**Issue by markddrake** [snowflakedb/snowflake-connector-nodejs#931]
Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of NodeJS driver are you using?

   
2. What operating system and processor architecture are you using?

   
3. What version of NodeJS are you using?
(`node --version` and `npm --version`)

4. What are the component versions in the environment (`npm list`)?

5.Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```
6. What did you do?

   If possible, provide a recipe for reproducing the error.
   A complete runnable program is good.

7. What did you expect to see?

   What should have happened and what happened instead?

8. Can you set logging to DEBUG and collect the logs?

   https://community.snowflake.com/s/article/How-to-generate-log-file-on-Snowflake-connectors

  e.g
  Add this to get standard output.

```
var snowflake = require('snowflake-sdk');
snowflake.configure(
{
  logLevel: 'trace'
});
```
   
9. What is your Snowflake account identifier, if any? (Optional)

**Comment by markddrake** [comment]
```
+-- snowflake-sdk@1.14.0

C:\Development\YADAMU>node -v
v22.2.0

yadamu@1.0.0 C:\Development\YADAMU\src
+-- @aws-sdk/client-s3@3.658.1
+-- @aws-sdk/lib-storage@3.658.1
+-- @azure/storage-blob@12.25.0
+-- @electron/remote@2.1.2
+-- bootstrap-icons@1.11.3
+-- bootstrap@5.3.3
+-- cookie-parser@1.4.6
+-- csv-parser@3.0.0
+-- electron-packager@17.1.2
+-- electron@32.1.2
+-- express-session@1.18.0
+-- express@4.21.0
+-- font-awesome@4.7.0
+-- ibm_db_electron@npm:ibm_db@3.2.4
+-- ibm_db@3.2.4
+-- install@0.13.0
+-- jquery@3.7.1
+-- mariadb@3.3.2
+-- mime-types@2.1.35
+-- mongodb@6.9.0
+-- mssql@11.0.1
+-- mysql@2.18.1
+-- mysql2@3.11.3
+-- npm@10.8.3
+-- oracledb@6.6.0
+-- pg-copy-streams@6.0.6
+-- pg-query-stream@4.7.0
+-- pg@8.13.0
+-- readable-stream@4.5.2
+-- snowflake-sdk@1.14.0
+-- uuid@10.0.0
`-- wkx@0.5.0
```
I get the following generated as soon as I attempt to use snowflake-sdk

````
{"level":"INFO","message":"[8:20:08.617 AM]: Connecting to GLOBAL Snowflake domain"}
{"level":"INFO","message":"[8:20:08.639 AM]: Trying to initialize Easy Logging"}
{"level":"INFO","message":"[8:20:08.645 AM]: No client config detected."}
{"level":"INFO","message":"[8:20:08.646 AM]: No config file path found. Client config will not be used."}
```

These messages should not appear by default...  - They mess up regression testing for starters.

My connection object looks like

{
  account: '####'
  username: '####'
  password: '####'
  warehouse: 'DEMO_WH',
  database: 'DEMO_DB',
  schema: 'PUBLIC',
  insecureConnect: true,
  arrayBindingThreshold: 10000000,
  user: undefined,
  host: undefined,
  port: undefined
}

```

**Comment by sfc-gh-dszmolka** [comment]
hi @markddrake i believe this is duplicate of #794  - please see [this comment](https://github.com/snowflakedb/snowflake-connector-nodejs/issues/794#issuecomment-2288608091) on options of reducing output, which we seem to be mandated to emit per our own Security team. apologies for the inconvenience.

**Comment by sfc-gh-dszmolka** [comment]
..would that help anything, if we were to modify the loglevel of the domain detector? (global vs china?) That's one single log line. The rest (related to Easy Logging feature) must stay I'm afraid.
