### ISSUE TITLE
SNOW-1769573: Support describeOnly

### ISSUE THREAD

**Issue by gabegorelick** [snowflakedb/snowflake-connector-nodejs#940]
## What is the current behavior?

The NodeJS client does not currently support the `describeOnly` setting to run a describe only query.

## What is the desired behavior?

`connection.execute({ /* other options not shown */, describeOnly: true })`

## How would this improve `snowflake-connector-nodejs`?

Bring the NodeJS client up to parity with other clients like `gosnowflake`, Java, and .NET that support `describeOnly`.

## References, Other Background

https://pkg.go.dev/github.com/snowflakedb/gosnowflake#WithDescribeOnly

https://github.com/snowflakedb/snowflake-jdbc/blob/83e5849103907f6b48a96c023233f2ca3e024a30/src/main/java/net/snowflake/client/core/SFStatement.java#L116

https://github.com/snowflakedb/snowflake-connector-net/blob/81995633744df22936f82e1d0f135b9b76f03945/Snowflake.Data/Core/SFStatement.cs#L223

**Comment by sfc-gh-dszmolka** [comment]
hi - thanks for raising this suggestion, and also the PR! the team will take a look.

**Comment by sfc-gh-dszmolka** [comment]
I see PR https://github.com/snowflakedb/snowflake-connector-nodejs/pull/945 has been merged

also released with Snowflake Node.js driver v1.15.0 October 2024 release cycle, so closing this issue.
