### ISSUE TITLE
SNOW-1789663: Resolve `@aws-sdk/node-http-handler@3.374.0` NPM deprecation warning

### ISSUE THREAD

**Issue by dar-yl** [snowflakedb/snowflake-connector-nodejs#947]
Related - `@azure/core-http@3.0.4` deprecation: https://github.com/snowflakedb/snowflake-connector-nodejs/issues/948

1. What version of NodeJS driver are you using?
`1.14.0`

3. What operating system and processor architecture are you using?
N/A

4. What version of NodeJS are you using?
Node: `20.17.0` / NPM: `10.8.2`

5. What are the component versions in the environment (`npm list`)?
    ```
    sandbox@0.0.0
    └── snowflake-sdk@1.14.0
     ```

6. What did you do?
Install the Node `snowflake-sdk@1.14.0`. Refer to NPM deprecation warnings...

    ```sh
    npm i snowflake-sdk@1.14.0
    npm warn deprecated @aws-sdk/node-http-handler@3.374.0: This package has moved to @smithy/node-http-handler
    # ...
    ```

7. What did you expect to see?
No deprecation warnings.

8. Can you collect debug logs?
N/A

**Comment by sfc-gh-dszmolka** [comment]
hi - thank you for drawing attention to this, not entirely sure why we need 2 separate issues but works for us. we'll look into this.

**Comment by DeveloperDaz** [comment]
@sfc-gh-dszmolka thanks and no worries - I wasn't sure how you'd prefer to approach it, figured the safer default was to split the issues :)
Happy to merge the 2 if you would prefer

**Comment by sfc-gh-dszmolka** [comment]
no worries , let's keep them separate for now, in case any issue with the dependency bump

**Comment by sfc-gh-dszmolka** [comment]
PR in draft https://github.com/snowflakedb/snowflake-connector-nodejs/pull/950

**Comment by sfc-gh-dszmolka** [comment]
PR merged, and will be part of the next version

**Comment by sfc-gh-dszmolka** [comment]
released with Snowflake Node.js driver v2.0.0
