### ISSUE TITLE
SNOW-1791788: Browser authentication timeout timer not cleared on successful authentication

### ISSUE THREAD

**Issue by adriancooney** [snowflakedb/snowflake-connector-nodejs#953]
If you need **urgent assistance** then [file a case with Snowflake Support](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge). 
Otherwise continue here. 

Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of NodeJS driver are you using?

1.14.0
   
3. What operating system and processor architecture are you using?

Operating System: Darwin (macOS)
Kernel Version: 23.6.0
Processor Architecture: ARM64

   
5. What version of NodeJS are you using?
(`node --version` and `npm --version`)

```
$ node -v
v22.5.1
$ pnpm -v
9.5.0
```

6. What are the component versions in the environment (`npm list`)?

7. What did you do?

1. Create a connection using `createConnection` with the `authenticator` set to `EXTERNALBROWSER`.
2. Call `connectAsync` which opens up browser tab.
3. Complete authentication flow successfully.
4. Execute simple query (< 3 seconds).
5. Close the connection.
6. Expect program to exit - it does not.

8. What did you expect to see?

Expect program to exit - it does not.

There is an open timer, [created here](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/master/lib/authentication/auth_web.js#L180-L183), preventing the program from exiting. The timer is essentially a timeout for the browser authentication. It should be cleared if the authentication was successful.

9. Can you collect debug logs?

```
[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 1 (tty) (stdio)
  - fd 2 (tty) (stdio)
- Timers:
  - (120000 ~ 2 min) (anonymous) @ ./node_modules/.pnpm/snowflake-sdk@1.14.0_asn1.js@5.4.1_debug@4.3.4_encoding@0.1.13/node_modules/snowflake-sdk/lib/authentication/auth_web.js:181
```

:warning: Before sharing any data, please be sure to review the log and remove any sensitive
information.

**Comment by sfc-gh-dszmolka** [comment]
hi - sounds like a duplicate to https://github.com/snowflakedb/snowflake-connector-nodejs/issues/846 
but thank you for the contribution! i'll close this issue as it doesn't need to exist, since it's a duplicate. However the PR still is useful.
