### ISSUE TITLE
SNOW-1800528: Disabling logging without anything being logged to stdout is difficult

### ISSUE THREAD

**Issue by visnup** [snowflakedb/snowflake-connector-nodejs#957]
Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of NodeJS driver are you using?
1.15.0
   
2. What operating system and processor architecture are you using?
darwin arm64
   
3. What version of NodeJS are you using?
v20.18.0

4. What are the component versions in the environment (`npm list`)?
N/A

5. What did you do?

```js
snowflake.configure({logLevel: "OFF"});
```

6. What did you expect to see?

No logging to stdout anywhere. Instead, I see the message
```json
{"level":"INFO","message":"[2:27:54.321 PM]: Configuring logger with level: -1, filePath: undefined, additionalLogToConsole: undefined"}
```
logged to console/stdout _before_ it finally turns off. This seems to defeat the purpose of silencing logging to stdout. This is important to me because the output to my program (querying Snowflake) is used as input to another process, and the downstream process is confused by seeing Snowflake logging output.

As a workaround, I've instead done

```js
import Logger from "snowflake-sdk/lib/logger.js";
Logger.getInstance().configure({level: -1});
```
but this isn't documented anywhere. Other workarounds like setting `additionalLogToConsole` to false doesn't work because a log file isn't set, and setting `logFilePath` also triggers that initial, unwanted message: https://github.com/snowflakedb/snowflake-connector-nodejs/blob/d50e1ce273ef945cd82ecd0a9480546134efe55b/lib/core.js#L189-L190

**Comment by sfc-gh-dszmolka** [comment]
hi - you're right, that's not how `OFF` loglevel intended to work. we'll take a look.

**Comment by sfc-gh-dszmolka** [comment]
PR https://github.com/snowflakedb/snowflake-connector-nodejs/pull/958

**Comment by velocityzen** [comment]
When is this going to be released? This is critical bug as it makes the whole STDOUT unusable.

**Comment by sfc-gh-dszmolka** [comment]
thank you for bearing with us while this is getting released! Currently, since we also need to consider other things which will be included in the release, there's unfortunately no precise estimation for the release date.  

Until then, you can try:
- `git clone` this repo
- `npm install` from `master` branch
- `require`ing the directory which has the `master` branch installed, instead of `snowflake-sdk`
which `master` branch already has the fix.

**Comment by visnup** [comment]
@velocityzen I also included a workaround above which is non-obvious but works for me for now.

**Comment by sfc-gh-dszmolka** [comment]
released with Snowflake Node.js driver v2.0.0
