### ISSUE TITLE
SNOW-151276: sdk-1.5.1 has package issue when using in a AWS lambda. asn1.js is excluded to package

### ISSUE THREAD

**Issue by jimfang** [snowflakedb/snowflake-connector-nodejs#99]
Please answer these questions before submitting your issue. Thanks!
The problem is simples described as no problem in the local machine. but has a problem in AWS lambda (version 1.5.1) .. .Both no problem with version 1.5.0.

Download the AWS lambda package, only asn1 in node_modules. in local, it has asn1 and asn1.js.
So, when running lambda, it raises exception.
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'asn1.js'\nRequire stack:\n- /var/task/node_modules/asn1.js-rfc2560/index.js\n- /var/task/node_modules/snowflake-sdk/lib/agent/check.js\n- /var/task/node_modules/snowflake-sdk/lib/agent/socket_util.js\n- /var/task/node_modules/snowflake-sdk/lib/agent/https_ocsp_agent.js\n- /var/task/node_modules/snowflake-sdk/lib/http/node.js\n- /var/task/node_modules/snowflake-sdk/lib/snowflake.js\n- /var/task/node_modules/snowflake-sdk/index.js\n- /var/task/src/internal/handler.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'asn1.js'",
        "Require stack:",
        "- /var/task/node_modules/asn1.js-rfc2560/index.js",
        "- /var/task/node_modules/snowflake-sdk/lib/agent/check.js",
        "- /var/task/node_modules/snowflake-sdk/lib/agent/socket_util.js",
        "- /var/task/node_modules/snowflake-sdk/lib/agent/https_ocsp_agent.js",
        "- /var/task/node_modules/snowflake-sdk/lib/http/node.js",
        "- /var/task/node_modules/snowflake-sdk/lib/snowflake.js",
        "- /var/task/node_modules/snowflake-sdk/index.js",
        "- /var/task/src/internal/handler.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1158:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)",
        "    at Module.load (internal/modules/cjs/loader.js:1002:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:901:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)",
        "    at internal/main/run_main_module.js:18:47"
    ]
}

1. What version of NodeJS are you using (`node --version` and `npm --version`)?
+ node --version
v12.14.1
+ npm --version
6.13.4

    "serverless": "^1.61.3",
    "serverless-webpack": "^5.3.0",

2. What operating system and processor architecture are you using?
Mac:
      System Version: macOS 10.15.3 (19D76)
      Kernel Version: Darwin 19.3.0
      Boot Volume: Macintosh HD

3. What are the component versions in the environment (`npm list`)?
- N/A as local no problem

4. What did you do?
downgrade 1.5.1 to 1.5.0, fix the lambda issue.

5. What did you expect to see?

6. What did you see instead?

7. Add this to get standard output.
 
```
var snowflake = require('./snowflake');
snowflake.configure(
{
  logLevel: 'trace'
});
```

**Comment by sfc-gh-dszmolka** [comment]
thank you for submitting the issue. it was probably resolved somewhere along the years, nowadays did not encounter such error message when testing Lambda with `v1.6.17` of the connector.
nevertheless; if you're still seeing this issue with the latest version of the connector, please reopen the issue and we'll take a look.
